import type { TechNode } from '../../engine/types';

// The hand-placed inner tree around the root. Positions and ids are stable —
// saves reference these directly. Everything further out is generated from
// the compact specs in majors/paths/clusters.
export const CORE: TechNode[] = [
  // ---- Root ------------------------------------------------------------------
  {
    id: 'basic_tools',
    name: 'Basic Tools',
    description: 'Gather efficiency +2%',
    cost: { wood: 3, water: 2 },
    researchTimeSeconds: 30,
    requires: [],
    effects: [{ kind: 'gatherEfficiency', resource: 'all', percent: 2 }],
    branch: 'magitech',
    x: 0,
    y: 0,
    major: true,
  },

  // ---- Magic branch (left) -----------------------------------------------------
  {
    id: 'attune_wood',
    name: 'Wood Attunement',
    description: 'Wood yield +1%',
    cost: { water: 5 },
    researchTimeSeconds: 45,
    requires: ['basic_tools'],
    effects: [{ kind: 'gatherEfficiency', resource: 'wood', percent: 1 }],
    branch: 'magic',
    x: -150,
    y: -90,
  },
  {
    id: 'attune_water',
    name: 'Water Attunement',
    description: 'Water yield +1%',
    cost: { wood: 5 },
    researchTimeSeconds: 45,
    requires: ['basic_tools'],
    effects: [{ kind: 'gatherEfficiency', resource: 'water', percent: 1 }],
    branch: 'magic',
    x: -150,
    y: 90,
  },
  {
    id: 'sap_flow',
    name: 'Sap Flow',
    description: 'Wood yield +1%',
    cost: { water: 10 },
    researchTimeSeconds: 90,
    requires: ['attune_wood'],
    effects: [{ kind: 'gatherEfficiency', resource: 'wood', percent: 1 }],
    branch: 'magic',
    x: -300,
    y: -180,
  },
  {
    id: 'spring_song',
    name: 'Spring Song',
    description: 'Water yield +1%',
    cost: { wood: 10 },
    researchTimeSeconds: 90,
    requires: ['attune_water'],
    effects: [{ kind: 'gatherEfficiency', resource: 'water', percent: 1 }],
    branch: 'magic',
    x: -300,
    y: 180,
  },
  {
    id: 'rope_making',
    name: 'Fiber Binding',
    description: 'Unlocks Fiber + Rope',
    cost: { wood: 8, water: 8 },
    researchTimeSeconds: 120,
    requires: ['attune_wood'],
    effects: [
      { kind: 'unlockResource', id: 'fiber' },
      { kind: 'unlockRecipe', id: 'rope' },
    ],
    branch: 'magic',
    x: -300,
    y: 0,
    major: true,
  },
  {
    id: 'verdant_whisper',
    name: 'Verdant Whisper',
    description: 'Gather efficiency +1%',
    cost: { fiber: 8 },
    researchTimeSeconds: 150,
    requires: ['rope_making'],
    effects: [{ kind: 'gatherEfficiency', resource: 'all', percent: 1 }],
    branch: 'magic',
    x: -450,
    y: 90,
  },
  {
    id: 'ley_sense',
    name: 'Ley Sense',
    description: 'Gather efficiency +1%',
    cost: { fiber: 8, water: 8 },
    researchTimeSeconds: 150,
    requires: ['rope_making'],
    effects: [{ kind: 'gatherEfficiency', resource: 'all', percent: 1 }],
    branch: 'magic',
    x: -450,
    y: -90,
  },
  {
    id: 'stone_spirits',
    name: 'Stone Spirits',
    description: 'Stone yield +1%',
    cost: { fiber: 12, water: 12 },
    researchTimeSeconds: 240,
    requires: ['ley_sense'],
    effects: [{ kind: 'gatherEfficiency', resource: 'stone', percent: 1 }],
    branch: 'magic',
    x: -600,
    y: -180,
  },
  {
    id: 'deep_roots',
    name: 'Deep Roots',
    description: 'Gather efficiency +1%',
    cost: { rope: 4 },
    researchTimeSeconds: 240,
    requires: ['verdant_whisper'],
    effects: [{ kind: 'gatherEfficiency', resource: 'all', percent: 1 }],
    branch: 'magic',
    x: -600,
    y: 0,
  },
  {
    id: 'moon_tides',
    name: 'Moon Tides',
    description: 'Water yield +1%',
    cost: { rope: 6, water: 20 },
    researchTimeSeconds: 360,
    requires: ['deep_roots'],
    effects: [{ kind: 'gatherEfficiency', resource: 'water', percent: 1 }],
    branch: 'magic',
    x: -750,
    y: 90,
  },

  // ---- Tech branch (right) ----------------------------------------------------
  {
    id: 'sharp_tools',
    name: 'Sharp Tools',
    description: 'Craft output +1%',
    cost: { wood: 6 },
    researchTimeSeconds: 45,
    requires: ['basic_tools'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 150,
    y: -90,
  },
  {
    id: 'measured_cuts',
    name: 'Measured Cuts',
    description: 'Craft output +1%',
    cost: { wood: 6, water: 3 },
    researchTimeSeconds: 45,
    requires: ['basic_tools'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 150,
    y: 90,
  },
  {
    id: 'woodworking',
    name: 'Woodworking',
    description: 'Unlocks Planks + Paper',
    cost: { wood: 10, water: 4 },
    researchTimeSeconds: 120,
    requires: ['sharp_tools'],
    effects: [
      { kind: 'unlockRecipe', id: 'planks' },
      { kind: 'unlockRecipe', id: 'paper' },
    ],
    branch: 'tech',
    x: 300,
    y: 0,
    major: true,
  },
  {
    id: 'quarrying',
    name: 'Quarrying',
    description: 'Unlocks Stone + Stone Bricks',
    cost: { wood: 12, water: 6 },
    researchTimeSeconds: 120,
    requires: ['sharp_tools'],
    effects: [
      { kind: 'unlockResource', id: 'stone' },
      { kind: 'unlockRecipe', id: 'stone_brick' },
    ],
    branch: 'tech',
    x: 300,
    y: -180,
    major: true,
  },
  {
    id: 'jigs',
    name: 'Jigs & Fixtures',
    description: 'Craft output +1%',
    cost: { wood: 12 },
    researchTimeSeconds: 90,
    requires: ['measured_cuts'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 300,
    y: 180,
  },
  {
    id: 'tight_tolerances',
    name: 'Tight Tolerances',
    description: 'Craft output +1%',
    cost: { plank: 6 },
    researchTimeSeconds: 180,
    requires: ['woodworking'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 450,
    y: 90,
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    description: 'Unlocks Copper + Iron Ore, Copper Ingots',
    cost: { stone: 15, wood: 20 },
    researchTimeSeconds: 240,
    requires: ['quarrying'],
    effects: [
      { kind: 'unlockResource', id: 'copper_ore' },
      { kind: 'unlockResource', id: 'iron_ore' },
      { kind: 'unlockRecipe', id: 'copper_ingot' },
    ],
    branch: 'tech',
    x: 450,
    y: -90,
    major: true,
  },
  {
    id: 'flux_baths',
    name: 'Flux Baths',
    description: 'Craft output +1%',
    cost: { stone_brick: 5 },
    researchTimeSeconds: 300,
    requires: ['metallurgy'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 600,
    y: -180,
  },
  {
    id: 'grindstones',
    name: 'Grindstones',
    description: 'Craft output +1%',
    cost: { plank: 8, stone: 10 },
    researchTimeSeconds: 300,
    requires: ['metallurgy', 'tight_tolerances'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 600,
    y: 60,
  },
  {
    id: 'blueprints',
    name: 'Blueprints',
    description: 'Craft output +1%',
    cost: { plank: 12, paper: 4 },
    researchTimeSeconds: 420,
    requires: ['grindstones'],
    effects: [{ kind: 'craftEfficiency', percent: 1 }],
    branch: 'tech',
    x: 750,
    y: 90,
  },

  // ---- Magitech spine (center) — requires one node from EACH side --------------
  {
    id: 'runic_saws',
    name: 'Runic Saws',
    description: 'Gather +1%, craft output +1%',
    cost: { wood: 12, water: 8 },
    researchTimeSeconds: 120,
    requires: ['attune_wood', 'sharp_tools'],
    effects: [
      { kind: 'gatherEfficiency', resource: 'all', percent: 1 },
      { kind: 'craftEfficiency', percent: 1 },
    ],
    branch: 'magitech',
    x: 0,
    y: -180,
  },
  {
    id: 'mana_lathe',
    name: 'Mana Lathe',
    description: 'Gather +1%, craft output +1%',
    cost: { wood: 12, water: 12 },
    researchTimeSeconds: 120,
    requires: ['attune_water', 'measured_cuts'],
    effects: [
      { kind: 'gatherEfficiency', resource: 'all', percent: 1 },
      { kind: 'craftEfficiency', percent: 1 },
    ],
    branch: 'magitech',
    x: 0,
    y: 180,
  },
  {
    id: 'spirit_pistons',
    name: 'Spirit Pistons',
    description: 'Gather +2%, craft output +2%',
    cost: { stone: 20, wood: 30, rope: 4 },
    researchTimeSeconds: 480,
    requires: ['runic_saws', 'ley_sense', 'quarrying'],
    effects: [
      { kind: 'gatherEfficiency', resource: 'all', percent: 2 },
      { kind: 'craftEfficiency', percent: 2 },
    ],
    branch: 'magitech',
    x: 0,
    y: -360,
    major: true,
  },
  {
    id: 'arcane_engine',
    name: 'Arcane Engine',
    description: 'Gather +2%, craft output +2%',
    cost: { plank: 12, rope: 6, stone_brick: 6 },
    researchTimeSeconds: 600,
    requires: ['mana_lathe', 'verdant_whisper', 'tight_tolerances'],
    effects: [
      { kind: 'gatherEfficiency', resource: 'all', percent: 2 },
      { kind: 'craftEfficiency', percent: 2 },
    ],
    branch: 'magitech',
    x: 0,
    y: 360,
    major: true,
  },
];
