import type { MajorSpec } from './specs';

// Era unlock majors on the expanded canvas. Connected majors sit ~600px apart
// so a 3-node path fits between them at ~150px pitch. `requires` lists the
// PREVIOUS MAJOR (or core node); where a PathSpec covers that edge the build
// step rewires the requirement through the path's small nodes. Cross-branch
// requirements (spine nodes needing one major from each side) stay direct
// long edges with no fillers.
//
// Balance: research time roughly doubles each era — minutes at the inner
// ring, hours mid-tree, a full day (86400s) on the final wonder majors.
// Costs lean on CRAFTED goods from earlier eras (tools, machines, potions),
// not just raws; `npm run validate` proves every cost is obtainable before
// the node that charges it.
export const MAJORS: MajorSpec[] = [
  // ---- Tech branch (right) ----------------------------------------------------
  { id: 'ironworking', name: 'Ironworking', description: 'Coal, iron smelting and basic metal stock', branch: 'tech', x: 1050, y: -90, requires: ['metallurgy'], cost: { copper_ingot: 12, stone_brick: 12, plank: 20 }, time: 600, resources: ['coal'], recipes: ['charcoal', 'iron_ingot', 'nails', 'iron_rod', 'iron_plate', 'copper_wire', 'gear', 'furnace', 'forge_bellows'] },
  { id: 'toolmaking', name: 'Toolmaking', description: 'Handles and the basic hand-tool set', branch: 'tech', x: 1350, y: 90, requires: ['blueprints'], cost: { iron_ingot: 12, plank: 24, copper_wire: 12 }, time: 900, recipes: ['handle', 'hammer', 'saw', 'chisel', 'hatchet', 'pickaxe', 'shovel'] },
  { id: 'carpentry', name: 'Carpentry', description: 'Beams, frames and wooden furniture', branch: 'tech', x: 1950, y: 90, requires: ['toolmaking'], cost: { plank: 40, nails: 36, saw: 2, hammer: 2 }, time: 1800, recipes: ['wooden_beam', 'wooden_frame', 'crate', 'bucket', 'table', 'chair', 'barrel'] },
  { id: 'claywork', name: 'Claywork', description: 'Clay pits, bricks, ceramics and the kiln', branch: 'tech', x: 1650, y: -450, requires: ['ironworking'], cost: { stone_brick: 24, iron_plate: 6, pickaxe: 2, water: 40 }, time: 1800, resources: ['clay'], recipes: ['brick', 'ceramic', 'pottery_dishes', 'kiln'] },
  { id: 'steelworks', name: 'Steelworks', description: 'Steel smelting and heavy metal stock', branch: 'tech', x: 1650, y: -90, requires: ['ironworking'], cost: { iron_plate: 10, coal: 40, furnace: 1, forge_bellows: 2 }, time: 1800, recipes: ['steel', 'steel_plate', 'blade', 'spring', 'bolt_kit', 'chain', 'anvil', 'scythe', 'blast_furnace'] },
  { id: 'glassworks', name: 'Glassworks', description: 'Quartz sand, glass and optics', branch: 'tech', x: 2250, y: -450, requires: ['claywork'], cost: { brick: 30, coal: 30, kiln: 1, ceramic: 8 }, time: 3600, resources: ['quartz_sand'], recipes: ['glass', 'lens', 'glass_tube', 'window', 'mirror', 'spyglass', 'vial', 'lantern'] },
  { id: 'mechanisms', name: 'Mechanisms', description: 'Wheels, gearboxes and simple machines', branch: 'tech', x: 2550, y: 210, requires: ['steelworks', 'carpentry'], cost: { gear: 24, plank: 40, steel: 10, chain: 4 }, time: 3600, recipes: ['hinge', 'bracket', 'crank', 'pulley_block', 'wheel', 'axle_assembly', 'gearbox', 'sawmill', 'waterwheel', 'windmill', 'loom_machine'] },
  { id: 'construction', name: 'Construction', description: 'Pillars, arches and fitted interiors', branch: 'tech', x: 2250, y: -210, requires: ['steelworks'], cost: { stone_brick: 60, steel: 12, hammer: 4, wooden_beam: 10 }, time: 3600, recipes: ['stone_pillar', 'arch', 'door', 'cabinet', 'workbench', 'stove'] },
  { id: 'fine_machinery', name: 'Fine Machinery', description: 'Precision instruments and clockwork', branch: 'tech', x: 3150, y: 390, requires: ['mechanisms'], cost: { gearbox: 6, glass: 16, spring: 12, copper_wire: 30 }, time: 7200, recipes: ['clock', 'music_box', 'printing_press', 'measuring_kit', 'hand_drill', 'wrench', 'magnifier'] },
  { id: 'transport', name: 'Transport', description: 'Carts and boats', branch: 'tech', x: 3750, y: 210, requires: ['fine_machinery'], cost: { wheel: 12, plank: 80, rope: 20, barrel: 4 }, time: 10800, recipes: ['cart', 'wheelbarrow', 'rowboat', 'sailboat'] },
  { id: 'everyday_engineering', name: 'Everyday Engineering', description: 'Machines for the home and the street', branch: 'tech', x: 3750, y: 570, requires: ['fine_machinery'], cost: { gearbox: 6, cloth: 16, spring: 12, clock: 2 }, time: 10800, recipes: ['bicycle', 'typewriter'] },
  { id: 'plumbing', name: 'Plumbing', description: 'Pipes, valves and pressure vessels', branch: 'tech', x: 3150, y: -90, requires: ['mechanisms'], cost: { copper_ingot: 30, gear: 12, iron_plate: 12, glass_tube: 6 }, time: 7200, recipes: ['pipe', 'valve', 'water_pump', 'bathtub', 'fountain', 'boiler'] },
  { id: 'chemistry', name: 'Chemistry', description: 'Sulfur, rubber and black powder', branch: 'tech', x: 2850, y: -450, requires: ['glassworks'], cost: { glass: 20, charcoal: 40, vial: 12, ceramic: 10 }, time: 7200, resources: ['sulfur'], recipes: ['black_powder', 'rubber', 'boots', 'umbrella', 'conveyor'] },
  { id: 'steam_power', name: 'Steam Power', description: 'Pistons, engines and powered workshops', branch: 'tech', x: 3750, y: -90, requires: ['plumbing'], cost: { boiler: 3, steel: 30, valve: 8, wrench: 2 }, time: 14400, recipes: ['piston', 'bearing', 'engine_block', 'steam_engine', 'lathe', 'crane', 'elevator'] },
  { id: 'railworks', name: 'Railworks', description: 'Rails and the iron horse', branch: 'tech', x: 4350, y: 90, requires: ['steam_power'], cost: { steel_plate: 16, wooden_beam: 24, steam_engine: 1, crane: 1 }, time: 21600, recipes: ['rail_track', 'locomotive'] },
  { id: 'oil_age', name: 'Oil Age', description: 'Crude oil, plastics and heavy drilling', branch: 'tech', x: 4350, y: -450, requires: ['steam_power', 'chemistry'], cost: { steel_plate: 12, engine_block: 3, boiler: 2, black_powder: 12 }, time: 21600, resources: ['crude_oil'], recipes: ['plastic', 'oil_pump', 'refinery', 'power_drill', 'drill_rig'] },
  { id: 'electricity', name: 'Electricity', description: 'Voltite, circuits and generators', branch: 'tech', x: 4950, y: -270, requires: ['oil_age'], cost: { copper_wire: 80, plastic: 30, engine_block: 4, refinery: 1 }, time: 28800, resources: ['voltite'], recipes: ['circuit', 'capacitor', 'voltite_cell', 'generator', 'arc_welder', 'arc_lamp'] },
  { id: 'communications', name: 'Communications', description: 'Wires that talk and light that remembers', branch: 'tech', x: 5550, y: -450, requires: ['electricity'], cost: { copper_wire: 120, circuit: 10, glass_tube: 12, capacitor: 8 }, time: 43200, recipes: ['telegraph', 'camera'] },
  { id: 'automation', name: 'Automation', description: 'Assemblers and automatons', branch: 'tech', x: 5550, y: -90, requires: ['electricity'], cost: { circuit: 16, steel_plate: 24, generator: 1, lathe: 1 }, time: 43200, recipes: ['assembler', 'automaton_frame', 'automaton'] },

  // ---- Magic branch (left) ------------------------------------------------------
  { id: 'herbalism', name: 'Herbalism', description: 'Herbs, extracts and incense', branch: 'magic', x: -1200, y: 0, requires: ['deep_roots'], cost: { water: 40, fiber: 24, rope: 8 }, time: 600, resources: ['herbs'], recipes: ['herbal_extract', 'spirit_water', 'incense'] },
  { id: 'sapcraft', name: 'Sapcraft', description: 'Resin tapping, glue and barkhide', branch: 'magic', x: -750, y: -450, requires: ['sap_flow'], cost: { wood: 60, water: 30, fiber: 20 }, time: 600, resources: ['resin'], recipes: ['glue', 'barkhide', 'ritual_candle'] },
  { id: 'weaving', name: 'Weaving', description: 'Cloth and everything sewn from it', branch: 'magic', x: -1350, y: 390, requires: ['moon_tides'], cost: { fiber: 60, rope: 12, water: 40 }, time: 900, recipes: ['cloth', 'basket', 'garment', 'satchel', 'bed', 'toolbelt'] },
  { id: 'alchemy', name: 'Alchemy', description: 'Salt, wards and the first potions', branch: 'magic', x: -1800, y: -210, requires: ['herbalism'], cost: { herbal_extract: 12, spirit_water: 12, incense: 8 }, time: 1800, resources: ['salt'], recipes: ['healing_potion', 'salt_ward'] },
  { id: 'ambercraft', name: 'Ambercraft', description: 'Amber pearls, charms and wands', branch: 'magic', x: -1800, y: 210, requires: ['herbalism'], cost: { resin: 30, fiber: 24, herbal_extract: 8 }, time: 1800, resources: ['amber'], recipes: ['amber_pearl', 'charm', 'wand'] },
  { id: 'scrivenery', name: 'Scrivenery', description: 'Enchanted ink, scrolls and grimoires', branch: 'magic', x: -2400, y: 0, requires: ['alchemy', 'ambercraft'], cost: { paper: 24, amber_pearl: 6, glue: 8, herbal_extract: 10 }, time: 3600, recipes: ['blank_scroll', 'enchanted_ink', 'scroll_of_growth', 'grimoire'] },
  { id: 'sporecraft', name: 'Sporecraft', description: 'Glowspores and living light', branch: 'magic', x: -2400, y: -450, requires: ['alchemy'], cost: { salt: 20, herbal_extract: 16, incense: 12 }, time: 3600, resources: ['glowspore'], recipes: ['glow_paste', 'glow_potion', 'glow_lamp'] },
  { id: 'lunar_rites', name: 'Lunar Rites', description: 'Moon dew, moon silver and elixirs', branch: 'magic', x: -2400, y: 450, requires: ['ambercraft'], cost: { amber_pearl: 10, spirit_water: 16, charm: 4, salt: 12 }, time: 3600, resources: ['moon_dew'], recipes: ['moon_elixir', 'moon_silver', 'moon_mirror', 'talisman'] },
  { id: 'vitalism', name: 'Vitalism', description: 'Life coaxed into vials and vats', branch: 'magic', x: -3000, y: -690, requires: ['sporecraft'], cost: { herbal_extract: 24, glowspore: 24, glow_paste: 8, spirit_water: 16 }, time: 7200, recipes: ['homunculus', 'vitae_flask'] },
  { id: 'divination', name: 'Divination', description: 'Cards, bowls and glimpses of tomorrow', branch: 'magic', x: -3000, y: 690, requires: ['lunar_rites'], cost: { moon_dew: 16, amber_pearl: 8, moon_elixir: 4, incense: 12 }, time: 7200, recipes: ['fortune_deck', 'singing_bowl'] },
  { id: 'crystal_attunement', name: 'Crystal Attunement', description: 'Mana crystals, dust and rune stones', branch: 'magic', x: -3000, y: 0, requires: ['scrivenery'], cost: { enchanted_ink: 10, moon_silver: 6, glow_paste: 6, grimoire: 2 }, time: 7200, resources: ['mana_crystal'], recipes: ['mana_dust', 'mana_potion', 'rune_stone', 'crystal_ball', 'rune_ring', 'staff'] },
  { id: 'high_rituals', name: 'High Rituals', description: 'Ritual kits, circles and totems', branch: 'magic', x: -3600, y: -210, requires: ['crystal_attunement', 'sporecraft'], cost: { rune_stone: 8, incense: 20, salt_ward: 4, ritual_candle: 12 }, time: 14400, recipes: ['ritual_kit', 'summoning_circle', 'warding_totem', 'spirit_lantern', 'philosophers_salt'] },
  { id: 'enchantment', name: 'Enchantment', description: 'Wearable magic and master arcana', branch: 'magic', x: -3600, y: 210, requires: ['crystal_attunement', 'lunar_rites'], cost: { mana_dust: 24, moon_silver: 8, talisman: 3, rune_ring: 2 }, time: 14400, recipes: ['amulet', 'enchanted_cloak', 'seven_league_boots', 'spellbook', 'archmage_wand'] },
  { id: 'ley_mastery', name: 'Ley Mastery', description: 'Ley essence and the deepest magic', branch: 'magic', x: -4200, y: 0, requires: ['high_rituals', 'enchantment'], cost: { rune_stone: 16, mana_dust: 40, summoning_circle: 2, amulet: 2 }, time: 28800, resources: ['ley_essence'], recipes: ['ley_thread', 'ley_chart', 'dream_catcher', 'transmutation_stone', 'phylactery', 'wishing_lamp', 'potion_of_plenty'] },

  // ---- Magitech spine (center) — requires one node from EACH side ---------------
  { id: 'rune_engineering', name: 'Rune Engineering', description: 'Inscribed plates, conduits and lenses', branch: 'magitech', x: 0, y: -900, requires: ['spirit_pistons', 'ironworking', 'ambercraft'], cost: { iron_plate: 10, amber_pearl: 8, gear: 10, enchanted_ink: 4 }, time: 3600, recipes: ['rune_plate', 'mana_conduit', 'crystal_lens', 'stained_glass', 'vase'] },
  { id: 'voltite_arcana', name: 'Voltite Arcana', description: 'Storm rods, mana batteries, rune circuits', branch: 'magitech', x: 0, y: -1440, requires: ['rune_engineering', 'electricity', 'high_rituals'], cost: { voltite_cell: 4, rune_stone: 10, capacitor: 6, ritual_kit: 4 }, time: 21600, recipes: ['storm_rod', 'mana_battery', 'rune_circuit', 'scroll_of_storms'] },
  { id: 'aetherworks', name: 'Aetherworks', description: 'Skyships and aether navigation', branch: 'magitech', x: 0, y: -1980, requires: ['voltite_arcana', 'ley_mastery'], cost: { ley_thread: 12, steel_plate: 20, mana_battery: 2, cloth: 30 }, time: 43200, recipes: ['skyship_balloon', 'skyship_hull', 'skyship', 'aether_compass'] },
  { id: 'wonders_of_spirit', name: 'Wonders of Spirit', description: 'Monuments of mana and moonlight', branch: 'magitech', x: 0, y: -2520, requires: ['aetherworks'], cost: { mana_battery: 8, transmutation_stone: 2, ley_thread: 16, moon_mirror: 2 }, time: 86400, recipes: ['mana_well', 'world_tree_sapling', 'floating_gardens', 'leyline_nexus', 'aurora_beacon', 'arcane_citadel'] },
  { id: 'golemcraft', name: 'Golemcraft', description: 'Golem cores and their bodies', branch: 'magitech', x: 0, y: 900, requires: ['arcane_engine', 'steelworks', 'crystal_attunement'], cost: { steel_plate: 8, rune_stone: 8, mana_dust: 16, anvil: 1 }, time: 7200, recipes: ['arcane_alloy', 'golem_core', 'stone_golem', 'iron_golem'] },
  { id: 'runic_industry', name: 'Runic Industry', description: 'Rune presses and enchanted workshops', branch: 'magitech', x: 0, y: 1440, requires: ['golemcraft', 'fine_machinery', 'scrivenery'], cost: { rune_stone: 6, gearbox: 4, rune_plate: 4, printing_press: 1 }, time: 14400, recipes: ['rune_press', 'lightning_loom', 'levitation_disc'] },
  { id: 'arcane_machinery', name: 'Arcane Machinery', description: 'Arcane alloy and mana engines', branch: 'magitech', x: 0, y: 1980, requires: ['runic_industry', 'steam_power'], cost: { engine_block: 3, mana_dust: 30, golem_core: 1, steel_plate: 10 }, time: 21600, recipes: ['mana_engine', 'clockwork_orrery', 'teleporter_frame'] },
  { id: 'thinking_machines', name: 'Thinking Machines', description: 'Engines that reason and guard', branch: 'magitech', x: 0, y: 2520, requires: ['arcane_machinery', 'automation'], cost: { automaton: 2, rune_circuit: 6, mana_battery: 3, clockwork_orrery: 1 }, time: 43200, recipes: ['thinking_engine', 'automaton_familiar', 'ward_turret', 'teleporter'] },
  { id: 'wonders_of_matter', name: 'Wonders of Matter', description: 'Monuments of steel and thought', branch: 'magitech', x: 0, y: 3060, requires: ['thinking_machines'], cost: { thinking_engine: 1, steel_plate: 40, arcane_alloy: 8, locomotive: 1 }, time: 86400, recipes: ['mana_reactor', 'colossus', 'grand_clocktower', 'observatory', 'philosophers_engine'] },
];
