import type { MajorSpec } from './specs';

// Era unlock majors on the expanded canvas. Connected majors sit ~600px apart
// so a 3-node path fits between them at ~150px pitch. `requires` lists the
// PREVIOUS MAJOR (or core node); where a PathSpec covers that edge the build
// step rewires the requirement through the path's small nodes. Cross-branch
// requirements (spine nodes needing one major from each side) stay direct
// long edges with no fillers.
export const MAJORS: MajorSpec[] = [
  // ---- Tech branch (right) ----------------------------------------------------
  { id: 'ironworking', name: 'Ironworking', description: 'Coal, iron smelting and basic metal stock', branch: 'tech', x: 1050, y: -90, requires: ['metallurgy'], cost: { copper_ingot: 4, stone: 10 }, time: 120, resources: ['coal'], recipes: ['charcoal', 'iron_ingot', 'nails', 'iron_rod', 'iron_plate', 'copper_wire', 'gear', 'furnace', 'forge_bellows'] },
  { id: 'toolmaking', name: 'Toolmaking', description: 'Handles and the basic hand-tool set', branch: 'tech', x: 1350, y: 90, requires: ['blueprints'], cost: { iron_ingot: 4, plank: 8 }, time: 150, recipes: ['handle', 'hammer', 'saw', 'chisel', 'hatchet', 'pickaxe', 'shovel'] },
  { id: 'carpentry', name: 'Carpentry', description: 'Beams, frames, paper and wooden furniture', branch: 'tech', x: 1950, y: 90, requires: ['toolmaking'], cost: { plank: 12, nails: 12 }, time: 180, recipes: ['wooden_beam', 'wooden_frame', 'paper', 'crate', 'bucket', 'table', 'chair', 'barrel'] },
  { id: 'claywork', name: 'Claywork', description: 'Clay pits, bricks, ceramics and the kiln', branch: 'tech', x: 1650, y: -450, requires: ['ironworking'], cost: { stone_brick: 8, water: 10 }, time: 180, resources: ['clay'], recipes: ['brick', 'ceramic', 'pottery_dishes', 'kiln'] },
  { id: 'steelworks', name: 'Steelworks', description: 'Steel smelting and heavy metal stock', branch: 'tech', x: 1650, y: -90, requires: ['ironworking'], cost: { iron_plate: 4, coal: 10 }, time: 240, recipes: ['steel', 'steel_plate', 'blade', 'spring', 'bolt_kit', 'chain', 'anvil', 'scythe', 'blast_furnace'] },
  { id: 'glassworks', name: 'Glassworks', description: 'Quartz sand, glass and optics', branch: 'tech', x: 2250, y: -450, requires: ['claywork'], cost: { brick: 8, coal: 6 }, time: 240, resources: ['quartz_sand'], recipes: ['glass', 'lens', 'glass_tube', 'window', 'mirror', 'spyglass', 'vial', 'lantern'] },
  { id: 'mechanisms', name: 'Mechanisms', description: 'Wheels, gearboxes and simple machines', branch: 'tech', x: 2550, y: 210, requires: ['steelworks', 'carpentry'], cost: { gear: 8, plank: 12 }, time: 300, recipes: ['hinge', 'bracket', 'crank', 'pulley_block', 'wheel', 'axle_assembly', 'gearbox', 'sawmill', 'waterwheel', 'windmill', 'loom_machine'] },
  { id: 'construction', name: 'Construction', description: 'Pillars, arches and fitted interiors', branch: 'tech', x: 2250, y: -210, requires: ['steelworks'], cost: { stone_brick: 16, iron_plate: 4 }, time: 300, recipes: ['stone_pillar', 'arch', 'door', 'cabinet', 'workbench', 'stove'] },
  { id: 'fine_machinery', name: 'Fine Machinery', description: 'Precision instruments and clockwork', branch: 'tech', x: 3150, y: 390, requires: ['mechanisms'], cost: { gearbox: 2, glass: 4 }, time: 360, recipes: ['clock', 'music_box', 'printing_press', 'measuring_kit', 'hand_drill', 'wrench', 'magnifier'] },
  { id: 'transport', name: 'Transport', description: 'Carts and boats', branch: 'tech', x: 3750, y: 210, requires: ['fine_machinery'], cost: { wheel: 4, plank: 20 }, time: 360, recipes: ['cart', 'wheelbarrow', 'rowboat', 'sailboat'] },
  { id: 'everyday_engineering', name: 'Everyday Engineering', description: 'Machines for the home and the street', branch: 'tech', x: 3750, y: 570, requires: ['fine_machinery'], cost: { gearbox: 2, cloth: 4 }, time: 420, recipes: ['bicycle', 'typewriter'] },
  { id: 'plumbing', name: 'Plumbing', description: 'Pipes, valves and pressure vessels', branch: 'tech', x: 3150, y: -90, requires: ['mechanisms'], cost: { copper_ingot: 8, gear: 4 }, time: 360, recipes: ['pipe', 'valve', 'water_pump', 'bathtub', 'fountain', 'boiler'] },
  { id: 'chemistry', name: 'Chemistry', description: 'Sulfur, rubber and black powder', branch: 'tech', x: 2850, y: -450, requires: ['glassworks'], cost: { glass: 6, charcoal: 10 }, time: 360, resources: ['sulfur'], recipes: ['black_powder', 'rubber', 'boots', 'umbrella', 'conveyor'] },
  { id: 'steam_power', name: 'Steam Power', description: 'Pistons, engines and powered workshops', branch: 'tech', x: 3750, y: -90, requires: ['plumbing'], cost: { boiler: 1, steel: 6 }, time: 480, recipes: ['piston', 'bearing', 'engine_block', 'steam_engine', 'lathe', 'crane', 'elevator'] },
  { id: 'railworks', name: 'Railworks', description: 'Rails and the iron horse', branch: 'tech', x: 4350, y: 90, requires: ['steam_power'], cost: { steel_plate: 4, wooden_beam: 6 }, time: 540, recipes: ['rail_track', 'locomotive'] },
  { id: 'oil_age', name: 'Oil Age', description: 'Crude oil, plastics and heavy drilling', branch: 'tech', x: 4350, y: -450, requires: ['steam_power', 'chemistry'], cost: { steel_plate: 4, engine_block: 1 }, time: 600, resources: ['crude_oil'], recipes: ['plastic', 'oil_pump', 'refinery', 'power_drill', 'drill_rig'] },
  { id: 'electricity', name: 'Electricity', description: 'Voltite, circuits and generators', branch: 'tech', x: 4950, y: -270, requires: ['oil_age'], cost: { copper_wire: 24, plastic: 8 }, time: 600, resources: ['voltite'], recipes: ['circuit', 'capacitor', 'voltite_cell', 'generator', 'arc_welder', 'arc_lamp'] },
  { id: 'communications', name: 'Communications', description: 'Wires that talk and light that remembers', branch: 'tech', x: 5550, y: -450, requires: ['electricity'], cost: { copper_wire: 20, circuit: 2 }, time: 720, recipes: ['telegraph', 'camera'] },
  { id: 'automation', name: 'Automation', description: 'Assemblers and automatons', branch: 'tech', x: 5550, y: -90, requires: ['electricity'], cost: { circuit: 4, steel_plate: 8 }, time: 900, recipes: ['assembler', 'automaton_frame', 'automaton'] },

  // ---- Magic branch (left) ------------------------------------------------------
  { id: 'herbalism', name: 'Herbalism', description: 'Herbs, extracts and incense', branch: 'magic', x: -1200, y: 0, requires: ['deep_roots'], cost: { water: 12, fiber: 8 }, time: 120, resources: ['herbs'], recipes: ['herbal_extract', 'spirit_water', 'incense'] },
  { id: 'sapcraft', name: 'Sapcraft', description: 'Resin tapping, glue and barkhide', branch: 'magic', x: -750, y: -450, requires: ['sap_flow'], cost: { wood: 20, water: 10 }, time: 120, resources: ['resin'], recipes: ['glue', 'barkhide', 'ritual_candle'] },
  { id: 'weaving', name: 'Weaving', description: 'Cloth and everything sewn from it', branch: 'magic', x: -1350, y: 390, requires: ['moon_tides'], cost: { fiber: 20, rope: 4 }, time: 150, recipes: ['cloth', 'basket', 'garment', 'satchel', 'bed', 'toolbelt'] },
  { id: 'alchemy', name: 'Alchemy', description: 'Salt, wards and the first potions', branch: 'magic', x: -1800, y: -210, requires: ['herbalism'], cost: { herbal_extract: 4, water: 12 }, time: 180, resources: ['salt'], recipes: ['healing_potion', 'salt_ward'] },
  { id: 'ambercraft', name: 'Ambercraft', description: 'Amber pearls, charms and wands', branch: 'magic', x: -1800, y: 210, requires: ['herbalism'], cost: { resin: 8, fiber: 8 }, time: 180, resources: ['amber'], recipes: ['amber_pearl', 'charm', 'wand'] },
  { id: 'scrivenery', name: 'Scrivenery', description: 'Enchanted ink, scrolls and grimoires', branch: 'magic', x: -2400, y: 0, requires: ['alchemy', 'ambercraft'], cost: { paper: 8, amber_pearl: 2 }, time: 240, recipes: ['blank_scroll', 'enchanted_ink', 'scroll_of_growth', 'grimoire'] },
  { id: 'sporecraft', name: 'Sporecraft', description: 'Glowspores and living light', branch: 'magic', x: -2400, y: -450, requires: ['alchemy'], cost: { salt: 6, herbal_extract: 4 }, time: 240, resources: ['glowspore'], recipes: ['glow_paste', 'glow_potion', 'glow_lamp'] },
  { id: 'lunar_rites', name: 'Lunar Rites', description: 'Moon dew, moon silver and elixirs', branch: 'magic', x: -2400, y: 450, requires: ['ambercraft'], cost: { amber_pearl: 4, spirit_water: 6 }, time: 300, resources: ['moon_dew'], recipes: ['moon_elixir', 'moon_silver', 'moon_mirror', 'talisman'] },
  { id: 'vitalism', name: 'Vitalism', description: 'Life coaxed into vials and vats', branch: 'magic', x: -3000, y: -690, requires: ['sporecraft'], cost: { herbal_extract: 6, glowspore: 6 }, time: 480, recipes: ['homunculus', 'vitae_flask'] },
  { id: 'divination', name: 'Divination', description: 'Cards, bowls and glimpses of tomorrow', branch: 'magic', x: -3000, y: 690, requires: ['lunar_rites'], cost: { moon_dew: 6, amber_pearl: 3 }, time: 420, recipes: ['fortune_deck', 'singing_bowl'] },
  { id: 'crystal_attunement', name: 'Crystal Attunement', description: 'Mana crystals, dust and rune stones', branch: 'magic', x: -3000, y: 0, requires: ['scrivenery'], cost: { enchanted_ink: 4, moon_silver: 2 }, time: 360, resources: ['mana_crystal'], recipes: ['mana_dust', 'mana_potion', 'rune_stone', 'crystal_ball', 'rune_ring', 'staff'] },
  { id: 'high_rituals', name: 'High Rituals', description: 'Ritual kits, circles and totems', branch: 'magic', x: -3600, y: -210, requires: ['crystal_attunement', 'sporecraft'], cost: { rune_stone: 3, incense: 6 }, time: 480, recipes: ['ritual_kit', 'summoning_circle', 'warding_totem', 'spirit_lantern', 'philosophers_salt'] },
  { id: 'enchantment', name: 'Enchantment', description: 'Wearable magic and master arcana', branch: 'magic', x: -3600, y: 210, requires: ['crystal_attunement', 'lunar_rites'], cost: { mana_dust: 8, moon_silver: 3 }, time: 480, recipes: ['amulet', 'enchanted_cloak', 'seven_league_boots', 'spellbook', 'archmage_wand'] },
  { id: 'ley_mastery', name: 'Ley Mastery', description: 'Ley essence and the deepest magic', branch: 'magic', x: -4200, y: 0, requires: ['high_rituals', 'enchantment'], cost: { rune_stone: 6, mana_dust: 12 }, time: 900, resources: ['ley_essence'], recipes: ['ley_thread', 'ley_chart', 'dream_catcher', 'transmutation_stone', 'phylactery', 'wishing_lamp', 'potion_of_plenty'] },

  // ---- Magitech spine (center) — requires one node from EACH side ---------------
  { id: 'rune_engineering', name: 'Rune Engineering', description: 'Inscribed plates, conduits and lenses', branch: 'magitech', x: 0, y: -900, requires: ['spirit_pistons', 'ironworking', 'ambercraft'], cost: { iron_plate: 4, amber_pearl: 4 }, time: 300, recipes: ['rune_plate', 'mana_conduit', 'crystal_lens', 'stained_glass', 'vase'] },
  { id: 'voltite_arcana', name: 'Voltite Arcana', description: 'Storm rods, mana batteries, rune circuits', branch: 'magitech', x: 0, y: -1440, requires: ['rune_engineering', 'electricity', 'high_rituals'], cost: { voltite_cell: 2, rune_stone: 4 }, time: 720, recipes: ['storm_rod', 'mana_battery', 'rune_circuit', 'scroll_of_storms'] },
  { id: 'aetherworks', name: 'Aetherworks', description: 'Skyships and aether navigation', branch: 'magitech', x: 0, y: -1980, requires: ['voltite_arcana', 'ley_mastery'], cost: { ley_thread: 6, steel_plate: 8 }, time: 1200, recipes: ['skyship_balloon', 'skyship_hull', 'skyship', 'aether_compass'] },
  { id: 'wonders_of_spirit', name: 'Wonders of Spirit', description: 'Monuments of mana and moonlight', branch: 'magitech', x: 0, y: -2520, requires: ['aetherworks'], cost: { mana_battery: 4, transmutation_stone: 1 }, time: 1800, recipes: ['mana_well', 'world_tree_sapling', 'floating_gardens', 'leyline_nexus', 'aurora_beacon', 'arcane_citadel'] },
  { id: 'golemcraft', name: 'Golemcraft', description: 'Golem cores and their bodies', branch: 'magitech', x: 0, y: 900, requires: ['arcane_engine', 'steelworks', 'crystal_attunement'], cost: { steel_plate: 4, rune_stone: 4 }, time: 600, recipes: ['golem_core', 'stone_golem', 'iron_golem'] },
  { id: 'runic_industry', name: 'Runic Industry', description: 'Rune presses and enchanted workshops', branch: 'magitech', x: 0, y: 1440, requires: ['golemcraft', 'fine_machinery', 'scrivenery'], cost: { rune_stone: 2, gearbox: 2 }, time: 600, recipes: ['rune_press', 'lightning_loom', 'levitation_disc'] },
  { id: 'arcane_machinery', name: 'Arcane Machinery', description: 'Arcane alloy and mana engines', branch: 'magitech', x: 0, y: 1980, requires: ['runic_industry', 'steam_power'], cost: { engine_block: 1, mana_dust: 12 }, time: 720, recipes: ['arcane_alloy', 'mana_engine', 'clockwork_orrery', 'teleporter_frame'] },
  { id: 'thinking_machines', name: 'Thinking Machines', description: 'Engines that reason and guard', branch: 'magitech', x: 0, y: 2520, requires: ['arcane_machinery', 'automation'], cost: { automaton: 1, rune_circuit: 2 }, time: 1200, recipes: ['thinking_engine', 'automaton_familiar', 'ward_turret', 'teleporter'] },
  { id: 'wonders_of_matter', name: 'Wonders of Matter', description: 'Monuments of steel and thought', branch: 'magitech', x: 0, y: 3060, requires: ['thinking_machines'], cost: { thinking_engine: 1, steel_plate: 16 }, time: 1800, recipes: ['mana_reactor', 'colossus', 'grand_clocktower', 'observatory', 'philosophers_engine'] },
];
