import type { Recipe, RecipeCategory, ResourceId } from '../engine/types';

// The full crafting catalog (~200 recipes), tiered as a pyramid:
//   raws (gathered) -> materials (~30) -> components/tools/goods -> machines,
//   arcana, magitech -> wonders.
//
// Design rules:
// - At most 3 distinct input TYPES per recipe (checked by `npm run validate`).
//   Late-game cost comes from quantities and chain depth, never more slots.
// - Every recipe outputs exactly one item type; cheap materials output batches.
// - Recipes start locked and unlock in themed batches via `unlockRecipe` tech
//   effects (unlocking a recipe also reveals its outputs).
const r = (
  id: string,
  name: string,
  icon: string,
  category: RecipeCategory,
  inputs: Record<ResourceId, number>,
  craftTimeSeconds: number,
  outputId?: ResourceId,
  outputCount = 1,
): Recipe => ({
  id,
  name,
  icon,
  category,
  inputs,
  outputs: { [outputId ?? id]: outputCount },
  craftTimeSeconds,
  unlockedByDefault: false,
});

export const RECIPES: Recipe[] = [
  // ===== MATERIALS ============================================================
  r('planks', 'Planks', '🪧', 'materials', { wood: 3 }, 30, 'plank', 2),
  r('rope', 'Rope', '🪢', 'materials', { fiber: 3 }, 30),
  r('stone_brick', 'Stone Brick', '🧱', 'materials', { stone: 2 }, 30),
  r('paper', 'Paper', '📄', 'materials', { wood: 2, water: 1 }, 30, undefined, 4),
  r('charcoal', 'Charcoal', '🌑', 'materials', { wood: 3 }, 45, undefined, 2),
  r('copper_ingot', 'Copper Ingot', '🥉', 'materials', { copper_ore: 2 }, 45),
  r('iron_ingot', 'Iron Ingot', '🔗', 'materials', { iron_ore: 2, charcoal: 1 }, 60),
  r('nails', 'Nails', '📌', 'materials', { iron_ingot: 1 }, 30, undefined, 12),
  r('iron_rod', 'Iron Rod', '🥢', 'materials', { iron_ingot: 1 }, 30, undefined, 2),
  r('iron_plate', 'Iron Plate', '🛡️', 'materials', { iron_ingot: 2 }, 45),
  r('copper_wire', 'Copper Wire', '➰', 'materials', { copper_ingot: 1 }, 30, undefined, 6),
  r('gear', 'Gear', '⚙️', 'materials', { iron_ingot: 1 }, 45, undefined, 2),
  r('brick', 'Brick', '🟥', 'materials', { clay: 2, charcoal: 1 }, 45, undefined, 3),
  r('ceramic', 'Ceramic', '🏺', 'materials', { clay: 2, water: 1 }, 45),
  r('cloth', 'Cloth', '🧵', 'materials', { fiber: 4 }, 45),
  r('glue', 'Glue', '🫙', 'materials', { resin: 2, water: 1 }, 30, undefined, 2),
  r('barkhide', 'Barkhide', '🥥', 'materials', { wood: 2, resin: 2 }, 45),
  r('herbal_extract', 'Herbal Extract', '🧪', 'materials', { herbs: 3, water: 1 }, 45, undefined, 2),
  r('spirit_water', 'Spirit Water', '💦', 'materials', { water: 2, herbs: 1 }, 30),
  r('steel', 'Steel', '⚔️', 'materials', { iron_ingot: 1, coal: 2 }, 90),
  r('steel_plate', 'Steel Plate', '🪖', 'materials', { steel: 2 }, 60),
  r('glass', 'Glass', '🥛', 'materials', { quartz_sand: 2, coal: 1 }, 60, undefined, 2),
  r('rubber', 'Rubber', '🧤', 'materials', { resin: 2, sulfur: 1 }, 60, undefined, 3),
  r('black_powder', 'Black Powder', '🎇', 'materials', { coal: 1, sulfur: 1, salt: 1 }, 60, undefined, 3),
  r('amber_pearl', 'Amber Pearl', '🟠', 'materials', { amber: 2, resin: 1 }, 60),
  r('enchanted_ink', 'Enchanted Ink', '🖋️', 'materials', { amber_pearl: 1, herbal_extract: 1, water: 1 }, 60, undefined, 2),
  r('glow_paste', 'Glow Paste', '🦠', 'materials', { glowspore: 2, water: 1 }, 45, undefined, 2),
  r('moon_silver', 'Moon Silver', '🥈', 'materials', { moon_dew: 2, copper_ingot: 1 }, 90),
  r('plastic', 'Plastic', '🥤', 'materials', { crude_oil: 1 }, 60, undefined, 4),
  r('mana_dust', 'Mana Dust', '💫', 'materials', { mana_crystal: 1 }, 60, undefined, 4),
  r('rune_stone', 'Rune Stone', '🪦', 'materials', { stone_brick: 1, mana_dust: 2 }, 90),
  r('ley_thread', 'Ley Thread', '🧶', 'materials', { ley_essence: 1, fiber: 2 }, 90, undefined, 3),
  r('voltite_cell', 'Voltite Cell', '🔋', 'materials', { voltite: 1, copper_wire: 2 }, 120),
  r('arcane_alloy', 'Arcane Alloy', '🌈', 'materials', { steel: 1, mana_dust: 2 }, 120),

  // ===== COMPONENTS ===========================================================
  r('handle', 'Handle', '🏏', 'components', { plank: 1, rope: 1 }, 45),
  r('wooden_beam', 'Wooden Beam', '🪜', 'components', { plank: 3, nails: 4 }, 60),
  r('wooden_frame', 'Wooden Frame', '🖼️', 'components', { wooden_beam: 2, glue: 1 }, 60),
  r('hinge', 'Hinge', '🦪', 'components', { iron_ingot: 1, nails: 2 }, 45, undefined, 2),
  r('bracket', 'Bracket', '🔲', 'components', { iron_plate: 1 }, 45, undefined, 4),
  r('crank', 'Crank', '🕹️', 'components', { iron_rod: 1, gear: 1 }, 60),
  r('pulley_block', 'Pulley Block', '🪝', 'components', { rope: 1, gear: 1, plank: 1 }, 60),
  r('wheel', 'Wheel', '🛞', 'components', { plank: 2, iron_rod: 1, bracket: 1 }, 60),
  r('axle_assembly', 'Axle Assembly', '🛼', 'components', { wheel: 2, iron_rod: 1 }, 90),
  r('gearbox', 'Gearbox', '🎛️', 'components', { gear: 4, iron_plate: 1 }, 90),
  r('spring', 'Spring', '〰️', 'components', { steel: 1 }, 45, undefined, 3),
  r('bolt_kit', 'Bolt Kit', '🔩', 'components', { steel: 1 }, 45, undefined, 6),
  r('chain', 'Chain', '⛓️', 'components', { iron_ingot: 2 }, 60),
  r('blade', 'Blade', '🔪', 'components', { steel: 1 }, 60, undefined, 2),
  r('stone_pillar', 'Stone Pillar', '🏛️', 'components', { stone_brick: 4 }, 90),
  r('arch', 'Arch', '⛩️', 'components', { brick: 4, glue: 1 }, 90),
  r('pipe', 'Pipe', '🚿', 'components', { copper_ingot: 1 }, 45, undefined, 2),
  r('valve', 'Valve', '🎚️', 'components', { pipe: 1, gear: 1, rubber: 1 }, 60),
  r('lens', 'Lens', '🔍', 'components', { glass: 2 }, 60),
  r('glass_tube', 'Glass Tube', '🧫', 'components', { glass: 1 }, 45, undefined, 2),
  r('piston', 'Piston', '💉', 'components', { steel: 1, iron_rod: 1 }, 90),
  r('bearing', 'Bearing', '⚪', 'components', { steel: 2 }, 60, undefined, 3),
  r('boiler', 'Boiler', '♨️', 'components', { iron_plate: 4, pipe: 2, valve: 1 }, 180),
  r('engine_block', 'Engine Block', '🧊', 'components', { piston: 2, gearbox: 1, iron_plate: 1 }, 240),
  r('circuit', 'Circuit', '🖥️', 'components', { copper_wire: 2, plastic: 1 }, 90),
  r('capacitor', 'Capacitor', '🪫', 'components', { copper_wire: 2, glass: 1 }, 90),
  r('crystal_lens', 'Crystal Lens', '💎', 'components', { lens: 1, mana_dust: 2 }, 120),
  r('rune_plate', 'Rune Plate', '🀄', 'components', { iron_plate: 1, enchanted_ink: 1 }, 120),
  r('mana_conduit', 'Mana Conduit', '🪈', 'components', { pipe: 1, mana_dust: 2 }, 120),
  r('rune_circuit', 'Rune Circuit', '⚛️', 'components', { circuit: 1, enchanted_ink: 1 }, 150),
  r('mana_battery', 'Mana Battery', '🔌', 'components', { voltite_cell: 1, mana_dust: 2, glass_tube: 1 }, 240),

  // ===== TOOLS ================================================================
  r('hammer', 'Hammer', '🔨', 'tools', { handle: 1, iron_ingot: 1 }, 90),
  r('saw', 'Saw', '🪚', 'tools', { handle: 1, iron_plate: 1 }, 90),
  r('chisel', 'Chisel', '🗡️', 'tools', { handle: 1, iron_rod: 1 }, 60),
  r('hatchet', 'Hatchet', '🪓', 'tools', { handle: 1, iron_ingot: 1 }, 90),
  r('pickaxe', 'Pickaxe', '⛏️', 'tools', { handle: 1, iron_ingot: 2 }, 120),
  r('shovel', 'Shovel', '🪏', 'tools', { handle: 1, iron_plate: 1 }, 90),
  r('anvil', 'Anvil', '🛠️', 'tools', { iron_plate: 3, stone_pillar: 1 }, 300),
  r('forge_bellows', 'Forge Bellows', '🪗', 'tools', { barkhide: 2, wooden_frame: 1 }, 120),
  r('scythe', 'Scythe', '🪃', 'tools', { blade: 1, wooden_beam: 1 }, 120),
  r('toolbelt', 'Toolbelt', '🎒', 'tools', { barkhide: 1, cloth: 1, nails: 4 }, 90),
  r('measuring_kit', 'Measuring Kit', '📐', 'tools', { paper: 2, iron_rod: 1, glass: 1 }, 90),
  r('hand_drill', 'Hand Drill', '🪛', 'tools', { crank: 1, iron_rod: 1, handle: 1 }, 120),
  r('wrench', 'Wrench', '🔧', 'tools', { steel: 1, handle: 1 }, 90),
  r('magnifier', 'Magnifier', '🔎', 'tools', { lens: 1, handle: 1 }, 90),
  r('power_drill', 'Power Drill', '⚒️', 'tools', { hand_drill: 1, engine_block: 1, rubber: 2 }, 300),
  r('arc_welder', 'Arc Welder', '💥', 'tools', { voltite_cell: 1, copper_wire: 4, lens: 1 }, 300),

  // ===== GOODS ================================================================
  r('bucket', 'Bucket', '🪣', 'goods', { plank: 2, rope: 1 }, 60),
  r('crate', 'Crate', '📦', 'goods', { plank: 4, nails: 6 }, 60),
  r('barrel', 'Barrel', '🥁', 'goods', { plank: 4, iron_plate: 1, glue: 1 }, 90),
  r('basket', 'Basket', '🧺', 'goods', { rope: 2, fiber: 2 }, 60),
  r('chair', 'Chair', '🪑', 'goods', { plank: 2, nails: 2, cloth: 1 }, 60),
  r('table', 'Table', '🛋️', 'goods', { plank: 3, wooden_beam: 1, nails: 4 }, 90),
  r('bed', 'Bed', '🛏️', 'goods', { wooden_frame: 2, cloth: 2, rope: 1 }, 120),
  r('cabinet', 'Cabinet', '🗄️', 'goods', { plank: 4, hinge: 2, nails: 6 }, 120),
  r('door', 'Door', '🚪', 'goods', { plank: 3, hinge: 2, handle: 1 }, 90),
  r('window', 'Window', '🪟', 'goods', { glass: 2, plank: 2 }, 90),
  r('lantern', 'Lantern', '🏮', 'goods', { glass: 1, copper_ingot: 1, rope: 1 }, 90),
  r('pottery_dishes', 'Dishes', '🍽️', 'goods', { ceramic: 2 }, 60, undefined, 4),
  r('vase', 'Painted Vase', '💐', 'goods', { ceramic: 1, enchanted_ink: 1 }, 90),
  r('mirror', 'Mirror', '🪞', 'goods', { glass: 2, copper_ingot: 1 }, 90),
  r('spyglass', 'Spyglass', '🔭', 'goods', { lens: 2, copper_ingot: 1 }, 120),
  r('clock', 'Clock', '🕰️', 'goods', { gearbox: 1, glass: 1, wooden_frame: 1 }, 240),
  r('music_box', 'Music Box', '🎵', 'goods', { gearbox: 1, wooden_frame: 1, enchanted_ink: 1 }, 240),
  r('stove', 'Stove', '🍳', 'goods', { iron_plate: 2, pipe: 1, brick: 2 }, 180),
  r('bathtub', 'Bathtub', '🛁', 'goods', { ceramic: 2, pipe: 1, valve: 1 }, 180),
  r('fountain', 'Fountain', '⛲', 'goods', { stone_pillar: 2, pipe: 1, valve: 1 }, 240),
  r('stained_glass', 'Stained Glass', '🌇', 'goods', { glass: 2, enchanted_ink: 1 }, 120),
  r('garment', 'Garment', '👘', 'goods', { cloth: 2, barkhide: 1 }, 90),
  r('boots', 'Boots', '🥾', 'goods', { barkhide: 2, rubber: 1 }, 90),
  r('satchel', 'Satchel', '👜', 'goods', { barkhide: 1, cloth: 1, rope: 1 }, 90),
  r('umbrella', 'Umbrella', '☂️', 'goods', { cloth: 1, iron_rod: 1, rubber: 1 }, 90),
  r('bicycle', 'Bicycle', '🚲', 'goods', { wheel: 2, chain: 1, spring: 1 }, 240),
  r('typewriter', 'Typewriter', '⌨️', 'goods', { gearbox: 1, spring: 2, iron_plate: 1 }, 300),
  r('telegraph', 'Telegraph', '📠', 'goods', { copper_wire: 6, capacitor: 1, wooden_frame: 1 }, 300),
  r('camera', 'Camera', '📷', 'goods', { lens: 2, capacitor: 1, wooden_frame: 1 }, 360),
  r('cart', 'Cart', '🛒', 'goods', { axle_assembly: 2, crate: 1, wooden_beam: 1 }, 240),
  r('wheelbarrow', 'Wheelbarrow', '🚜', 'goods', { wheel: 1, crate: 1, handle: 2 }, 120),
  r('rowboat', 'Rowboat', '🛶', 'goods', { plank: 6, glue: 2, cloth: 1 }, 240),
  r('sailboat', 'Sailboat', '⛵', 'goods', { rowboat: 1, cloth: 2, rope: 2 }, 300),
  r('glow_lamp', 'Glow Lamp', '💡', 'goods', { glass_tube: 1, glow_paste: 1, copper_ingot: 1 }, 120),
  r('arc_lamp', 'Arc Lamp', '🔦', 'goods', { glass_tube: 1, copper_wire: 2, voltite: 1 }, 180),

  // ===== MACHINES =============================================================
  r('workbench', 'Workbench', '🧰', 'machines', { table: 1, hammer: 1, saw: 1 }, 300),
  r('sawmill', 'Sawmill', '🛖', 'machines', { wooden_frame: 1, blade: 1, crank: 1 }, 300),
  r('kiln', 'Kiln', '🌋', 'machines', { brick: 8, iron_plate: 1 }, 300),
  r('furnace', 'Furnace', '🔥', 'machines', { stone_brick: 6, iron_plate: 1, forge_bellows: 1 }, 300),
  r('blast_furnace', 'Blast Furnace', '🧨', 'machines', { furnace: 1, steel_plate: 4, boiler: 1 }, 600),
  r('loom_machine', 'Loom', '🕸️', 'machines', { wooden_frame: 1, gear: 2, crank: 1 }, 300),
  r('printing_press', 'Printing Press', '📰', 'machines', { gearbox: 1, iron_plate: 1, wooden_frame: 1 }, 300),
  r('water_pump', 'Water Pump', '🚰', 'machines', { pipe: 1, piston: 1, valve: 1 }, 300),
  r('windmill', 'Windmill', '🌬️', 'machines', { cloth: 2, wooden_beam: 2, gearbox: 1 }, 300),
  r('waterwheel', 'Waterwheel', '🎡', 'machines', { wheel: 2, wooden_beam: 1, gear: 1 }, 300),
  r('steam_engine', 'Steam Engine', '💨', 'machines', { boiler: 1, engine_block: 1, chain: 1 }, 600),
  r('lathe', 'Lathe', '🗜️', 'machines', { engine_block: 1, blade: 1, iron_plate: 1 }, 450),
  r('crane', 'Crane', '🏗️', 'machines', { pulley_block: 2, chain: 1, steel_plate: 1 }, 450),
  r('elevator', 'Elevator', '🛗', 'machines', { crane: 1, steel_plate: 1, rope: 4 }, 450),
  r('conveyor', 'Conveyor', '➿', 'machines', { rubber: 2, iron_rod: 2, gear: 1 }, 240),
  r('rail_track', 'Rail Track', '🛤️', 'machines', { steel: 2, wooden_beam: 1 }, 90, undefined, 2),
  r('locomotive', 'Locomotive', '🚂', 'machines', { steam_engine: 1, rail_track: 4, steel_plate: 2 }, 900),
  r('oil_pump', 'Oil Pump', '⛽', 'machines', { water_pump: 1, steam_engine: 1, steel_plate: 1 }, 600),
  r('refinery', 'Refinery', '🏭', 'machines', { boiler: 1, valve: 2, pipe: 4 }, 600),
  r('drill_rig', 'Drill Rig', '🗼', 'machines', { power_drill: 1, steam_engine: 1, steel_plate: 2 }, 900),
  r('generator', 'Generator', '🌪️', 'machines', { steam_engine: 1, voltite_cell: 1, copper_wire: 4 }, 900),
  r('assembler', 'Assembler', '🦾', 'machines', { lathe: 1, circuit: 2, gearbox: 1 }, 900),
  r('automaton_frame', 'Automaton Frame', '🪆', 'machines', { steel_plate: 2, gearbox: 1, spring: 2 }, 450),
  r('automaton', 'Automaton', '🤖', 'machines', { automaton_frame: 1, circuit: 1, voltite_cell: 1 }, 900),

  // ===== ARCANA ===============================================================
  r('incense', 'Incense', '🌫️', 'arcana', { herbs: 2, resin: 1 }, 45, undefined, 3),
  r('ritual_candle', 'Ritual Candle', '🕯️', 'arcana', { resin: 2, fiber: 1 }, 45, undefined, 2),
  r('vial', 'Glass Vial', '🧴', 'arcana', { glass: 1 }, 45, undefined, 3),
  r('healing_potion', 'Healing Potion', '❤️', 'arcana', { vial: 1, herbal_extract: 1, spirit_water: 1 }, 90),
  r('mana_potion', 'Mana Potion', '💙', 'arcana', { vial: 1, mana_dust: 1, spirit_water: 1 }, 90),
  r('glow_potion', 'Glow Potion', '🍸', 'arcana', { vial: 1, glow_paste: 1 }, 90),
  r('moon_elixir', 'Moon Elixir', '🌜', 'arcana', { vial: 1, moon_dew: 2, herbal_extract: 1 }, 120),
  r('salt_ward', 'Salt Ward', '🧿', 'arcana', { salt: 2, rune_stone: 1, paper: 1 }, 120),
  r('blank_scroll', 'Blank Scroll', '📜', 'arcana', { paper: 2, glue: 1 }, 60, undefined, 2),
  r('scroll_of_growth', 'Scroll of Growth', '🌱', 'arcana', { blank_scroll: 1, enchanted_ink: 1, herbal_extract: 1 }, 120),
  r('scroll_of_storms', 'Scroll of Storms', '⛈️', 'arcana', { blank_scroll: 1, enchanted_ink: 1, voltite: 1 }, 240),
  r('grimoire', 'Grimoire', '📕', 'arcana', { blank_scroll: 4, barkhide: 1, enchanted_ink: 1 }, 240),
  r('wand', 'Wand', '🪄', 'arcana', { handle: 1, amber_pearl: 1 }, 90),
  r('staff', 'Staff', '🦯', 'arcana', { wooden_beam: 1, mana_crystal: 1, rope: 1 }, 180),
  r('charm', 'Charm', '🧧', 'arcana', { amber_pearl: 1, rope: 1 }, 90),
  r('talisman', 'Talisman', '🪬', 'arcana', { moon_silver: 1, barkhide: 1, enchanted_ink: 1 }, 180),
  r('rune_ring', 'Rune Ring', '💍', 'arcana', { moon_silver: 1, mana_dust: 1 }, 180),
  r('amulet', 'Amulet', '📿', 'arcana', { charm: 1, moon_silver: 1, enchanted_ink: 1 }, 240),
  r('crystal_ball', 'Crystal Ball', '🔮', 'arcana', { glass: 2, mana_crystal: 1 }, 240),
  r('ritual_kit', 'Ritual Kit', '🎎', 'arcana', { ritual_candle: 2, incense: 2, salt: 1 }, 120),
  r('summoning_circle', 'Summoning Circle', '🔯', 'arcana', { ritual_kit: 1, rune_stone: 2, mana_dust: 2 }, 300),
  r('spirit_lantern', 'Spirit Lantern', '🎐', 'arcana', { lantern: 1, glow_paste: 1, mana_dust: 1 }, 180),
  r('moon_mirror', 'Moon Mirror', '🌕', 'arcana', { mirror: 1, moon_dew: 2, moon_silver: 1 }, 300),
  r('fortune_deck', 'Fortune Deck', '🎴', 'arcana', { paper: 4, enchanted_ink: 1, amber_pearl: 1 }, 180),
  r('singing_bowl', 'Singing Bowl', '🥣', 'arcana', { copper_ingot: 2, moon_silver: 1 }, 240),
  r('homunculus', 'Homunculus', '🧌', 'arcana', { vial: 2, herbal_extract: 4, mana_dust: 2 }, 600),
  r('vitae_flask', 'Vitae Flask', '⚱️', 'arcana', { vial: 1, healing_potion: 1, glow_paste: 1 }, 300),
  r('dream_catcher', 'Dream Catcher', '💤', 'arcana', { rope: 2, ley_thread: 1, charm: 1 }, 240),
  r('enchanted_cloak', 'Enchanted Cloak', '🧥', 'arcana', { garment: 1, ley_thread: 1, mana_dust: 2 }, 300),
  r('seven_league_boots', 'Seven-League Boots', '👢', 'arcana', { boots: 1, ley_thread: 1, moon_elixir: 1 }, 300),
  r('philosophers_salt', "Philosopher's Salt", '❄️', 'arcana', { salt: 2, mana_dust: 1, moon_dew: 1 }, 240),
  r('transmutation_stone', 'Transmutation Stone', '🪩', 'arcana', { philosophers_salt: 1, rune_stone: 2, amber_pearl: 1 }, 600),
  r('potion_of_plenty', 'Potion of Plenty', '🏆', 'arcana', { healing_potion: 1, moon_elixir: 1, philosophers_salt: 1 }, 450),
  r('warding_totem', 'Warding Totem', '🎭', 'arcana', { wooden_beam: 1, rune_stone: 2, salt_ward: 1 }, 450),
  r('ley_chart', 'Ley Chart', '🗺️', 'arcana', { paper: 2, enchanted_ink: 1, ley_thread: 1 }, 300),
  r('spellbook', 'Spellbook', '📖', 'arcana', { grimoire: 1, enchanted_ink: 2, mana_dust: 1 }, 450),
  r('archmage_wand', 'Archmage Wand', '☄️', 'arcana', { wand: 1, mana_crystal: 1, moon_silver: 1 }, 450),
  r('phylactery', 'Phylactery', '⚗️', 'arcana', { vial: 1, transmutation_stone: 1, moon_silver: 1 }, 900),
  r('wishing_lamp', 'Wishing Lamp', '🪔', 'arcana', { lantern: 1, moon_silver: 1, philosophers_salt: 1 }, 900),

  // ===== MAGITECH =============================================================
  r('golem_core', 'Golem Core', '🫀', 'magitech', { mana_crystal: 1, rune_stone: 1, arcane_alloy: 1 }, 600),
  r('stone_golem', 'Stone Golem', '🗿', 'magitech', { golem_core: 1, stone_pillar: 4, rune_stone: 2 }, 900),
  r('iron_golem', 'Iron Golem', '🦿', 'magitech', { golem_core: 1, steel_plate: 4, automaton_frame: 1 }, 900),
  r('mana_engine', 'Mana Engine', '💠', 'magitech', { engine_block: 1, mana_battery: 1, mana_conduit: 1 }, 900),
  r('clockwork_orrery', 'Clockwork Orrery', '🪐', 'magitech', { gearbox: 2, crystal_lens: 1, moon_silver: 1 }, 600),
  r('teleporter_frame', 'Teleporter Frame', '🌀', 'magitech', { arcane_alloy: 2, rune_stone: 2, steel_plate: 1 }, 600),
  r('teleporter', 'Teleporter', '🌌', 'magitech', { teleporter_frame: 1, mana_battery: 1, ley_chart: 1 }, 1200),
  r('aether_compass', 'Aether Compass', '🧭', 'magitech', { rune_circuit: 1, moon_silver: 1, glass: 1 }, 600),
  r('rune_press', 'Rune Press', '🖨️', 'magitech', { printing_press: 1, rune_plate: 1, mana_dust: 4 }, 900),
  r('lightning_loom', 'Lightning Loom', '🪡', 'magitech', { loom_machine: 1, voltite_cell: 1, ley_thread: 2 }, 900),
  r('levitation_disc', 'Levitation Disc', '🥏', 'magitech', { rune_plate: 1, moon_silver: 2, ley_thread: 1 }, 600),
  r('storm_rod', 'Storm Rod', '🌩️', 'magitech', { voltite: 1, iron_rod: 2, rune_stone: 1 }, 600),
  r('ward_turret', 'Ward Turret', '📡', 'magitech', { automaton_frame: 1, rune_circuit: 1, crystal_lens: 1 }, 900),
  r('thinking_engine', 'Thinking Engine', '🧠', 'magitech', { assembler: 1, rune_circuit: 2, mana_battery: 1 }, 1800),
  r('automaton_familiar', 'Automaton Familiar', '🐦', 'magitech', { automaton: 1, golem_core: 1, enchanted_ink: 1 }, 1200),
  r('skyship_balloon', 'Skyship Balloon', '🎈', 'magitech', { cloth: 4, rope: 2, ley_thread: 1 }, 600),
  r('skyship_hull', 'Skyship Hull', '🚢', 'magitech', { sailboat: 1, steel_plate: 4, arcane_alloy: 2 }, 1200),
  r('skyship', 'Skyship', '🛸', 'magitech', { skyship_hull: 1, skyship_balloon: 1, mana_engine: 1 }, 1800),
  r('mana_reactor', 'Mana Reactor', '☢️', 'magitech', { mana_engine: 1, mana_battery: 2, arcane_alloy: 1 }, 1800),

  // ===== WONDERS ==============================================================
  r('grand_clocktower', 'Grand Clocktower', '🏰', 'wonders', { clock: 4, stone_pillar: 8, thinking_engine: 1 }, 3600),
  r('observatory', 'Observatory', '🌠', 'wonders', { clockwork_orrery: 1, arch: 6, lens: 4 }, 2400),
  r('mana_well', 'Mana Well', '🕳️', 'wonders', { mana_reactor: 1, rune_stone: 8, mana_conduit: 4 }, 3600),
  r('world_tree_sapling', 'World Tree Sapling', '🌳', 'wonders', { transmutation_stone: 1, herbal_extract: 8, spirit_water: 8 }, 2400),
  r('floating_gardens', 'Floating Gardens', '🏝️', 'wonders', { world_tree_sapling: 1, warding_totem: 4, fountain: 2 }, 3600),
  r('colossus', 'Colossus', '🗽', 'wonders', { iron_golem: 2, stone_golem: 2, mana_reactor: 1 }, 3600),
  r('leyline_nexus', 'Leyline Nexus', '🌐', 'wonders', { teleporter: 1, ley_thread: 4, mana_well: 1 }, 3600),
  r('aurora_beacon', 'Aurora Beacon', '🎆', 'wonders', { storm_rod: 4, mana_battery: 4, crystal_lens: 1 }, 3600),
  r('philosophers_engine', "Philosopher's Engine", '♾️', 'wonders', { thinking_engine: 1, transmutation_stone: 1, phylactery: 1 }, 3600),
  r('arcane_citadel', 'Arcane Citadel', '🏯', 'wonders', { arch: 12, colossus: 1, leyline_nexus: 1 }, 3600),
];

export const RECIPE_BY_ID: Record<string, Recipe> = Object.fromEntries(
  RECIPES.map((recipe) => [recipe.id, recipe]),
);

// Display order for grouped views.
export const CATEGORY_ORDER: { id: RecipeCategory; label: string; icon: string }[] = [
  { id: 'materials', label: 'Materials', icon: '🧱' },
  { id: 'components', label: 'Components', icon: '⚙️' },
  { id: 'tools', label: 'Tools', icon: '🔨' },
  { id: 'goods', label: 'Goods', icon: '🪑' },
  { id: 'machines', label: 'Machines', icon: '🏭' },
  { id: 'arcana', label: 'Arcana', icon: '🔮' },
  { id: 'magitech', label: 'Magitech', icon: '⚡' },
  { id: 'wonders', label: 'Wonders', icon: '🏰' },
];
