import type { ResourceDef } from '../engine/types';

// All resources AND crafted items live here — the engine treats them uniformly.
// To add a new resource: add an entry (harvestAmount > 0 makes it gatherable by
// workers in the Gather view) and, if it starts locked, add an `unlockResource`
// effect to a tech node in tech.ts. Crafted items (harvestAmount 0) are
// revealed automatically when a recipe producing them unlocks.
//
// Sell prices follow a rough rule of thumb: raws scale ~2.5× per tier, crafted
// items sell for ~1.4× the value of their inputs. Tuned by feel, not formula.

// helpers keep the 200+ entry catalog readable: one line per entry.
const raw = (
  id: string,
  name: string,
  icon: string,
  tier: number,
  baseSellPrice: number,
  extractTimeSeconds: number,
  unlockedByDefault = false,
): ResourceDef => ({ id, name, icon, tier, baseSellPrice, unlockedByDefault, harvestAmount: 1, extractTimeSeconds });

const item = (id: string, name: string, icon: string, tier: number, baseSellPrice: number): ResourceDef => ({
  id,
  name,
  icon,
  tier,
  baseSellPrice,
  unlockedByDefault: false,
  harvestAmount: 0,
  extractTimeSeconds: 0,
});

export const RESOURCES: ResourceDef[] = [
  // ---- Gatherable raws (20) --------------------------------------------------
  raw('wood', 'Wood', '🪵', 0, 1, 60, true),
  raw('water', 'Water', '💧', 0, 1, 60, true),
  raw('stone', 'Stone', '🪨', 1, 3, 60),
  raw('fiber', 'Fiber', '🌾', 1, 3, 60),
  raw('clay', 'Clay', '🟤', 2, 8, 90),
  raw('copper_ore', 'Copper Ore', '🟠', 2, 8, 90),
  raw('iron_ore', 'Iron Ore', '🔩', 2, 10, 90),
  raw('herbs', 'Herbs', '🌿', 2, 9, 90),
  raw('resin', 'Resin', '🍯', 2, 9, 90),
  raw('coal', 'Coal', '⚫', 3, 15, 120),
  raw('salt', 'Salt', '🧂', 3, 18, 120),
  raw('amber', 'Amber', '🔶', 3, 22, 120),
  raw('quartz_sand', 'Quartz Sand', '⏳', 4, 35, 180),
  raw('sulfur', 'Sulfur', '🟡', 4, 40, 180),
  raw('glowspore', 'Glowspore', '🍄', 4, 45, 180),
  raw('moon_dew', 'Moon Dew', '🌙', 4, 50, 180),
  raw('crude_oil', 'Crude Oil', '🛢️', 5, 120, 300),
  raw('mana_crystal', 'Mana Crystal', '🔮', 5, 130, 300),
  raw('voltite', 'Voltite', '⚡', 6, 320, 600),
  raw('ley_essence', 'Ley Essence', '✨', 6, 340, 600),

  // ---- Materials (refined; tier ~= progression order) -------------------------
  item('plank', 'Plank', '🟫', 1, 4),
  item('rope', 'Rope', '🪢', 1, 12),
  item('stone_brick', 'Stone Brick', '🧱', 1, 9),
  item('paper', 'Paper', '📄', 1, 2),
  item('charcoal', 'Charcoal', '🪵', 2, 4),
  item('copper_ingot', 'Copper Ingot', '🥉', 2, 20),
  item('iron_ingot', 'Iron Ingot', '⛓️', 2, 32),
  item('nails', 'Nails', '📌', 2, 4),
  item('iron_rod', 'Iron Rod', '🥢', 2, 22),
  item('iron_plate', 'Iron Plate', '⬜', 2, 90),
  item('copper_wire', 'Copper Wire', '🌀', 2, 5),
  item('gear', 'Gear', '⚙️', 2, 25),
  item('brick', 'Brick', '🟥', 2, 10),
  item('ceramic', 'Ceramic', '🏺', 2, 25),
  item('cloth', 'Cloth', '🧵', 2, 18),
  item('glue', 'Glue', '🫙', 2, 14),
  item('barkhide', 'Barkhide', '🟤', 2, 28),
  item('herbal_extract', 'Herbal Extract', '🧪', 2, 20),
  item('spirit_water', 'Spirit Water', '💦', 2, 8),
  item('steel', 'Steel', '🔗', 3, 90),
  item('steel_plate', 'Steel Plate', '⏹️', 3, 250),
  item('glass', 'Glass', '🪟', 3, 60),
  item('rubber', 'Rubber', '⬛', 3, 27),
  item('black_powder', 'Black Powder', '🎇', 3, 34),
  item('amber_pearl', 'Amber Pearl', '🟠', 3, 75),
  item('enchanted_ink', 'Enchanted Ink', '🖋️', 3, 60),
  item('glow_paste', 'Glow Paste', '🟢', 4, 65),
  item('moon_silver', 'Moon Silver', '🥈', 4, 170),
  item('plastic', 'Plastic', '📦', 4, 45),
  item('mana_dust', 'Mana Dust', '💫', 4, 45),
  item('rune_stone', 'Rune Stone', '🪬', 5, 140),
  item('ley_thread', 'Ley Thread', '🧶', 5, 160),
  item('voltite_cell', 'Voltite Cell', '🔋', 6, 470),
  item('arcane_alloy', 'Arcane Alloy', '🌈', 6, 260),

  // ---- Components -------------------------------------------------------------
  item('handle', 'Handle', '🖇️', 2, 25),
  item('wooden_beam', 'Wooden Beam', '🪜', 2, 40),
  item('wooden_frame', 'Wooden Frame', '🖼️', 2, 130),
  item('hinge', 'Hinge', '🚪', 2, 45),
  item('bracket', 'Bracket', '🔲', 2, 35),
  item('crank', 'Crank', '🔧', 2, 70),
  item('pulley_block', 'Pulley Block', '🛞', 2, 60),
  item('wheel', 'Wheel', '⭕', 3, 90),
  item('axle_assembly', 'Axle Assembly', '🛒', 3, 300),
  item('gearbox', 'Gearbox', '🎛️', 3, 300),
  item('spring', 'Spring', '〰️', 3, 45),
  item('bolt_kit', 'Bolt Kit', '🔩', 3, 25),
  item('chain', 'Chain', '⛓️', 3, 100),
  item('blade', 'Blade', '🔪', 3, 70),
  item('stone_pillar', 'Stone Pillar', '🗿', 3, 55),
  item('arch', 'Arch', '⛩️', 3, 75),
  item('pipe', 'Pipe', '🚿', 3, 30),
  item('valve', 'Valve', '🎚️', 3, 130),
  item('lens', 'Lens', '🔍', 3, 180),
  item('glass_tube', 'Glass Tube', '🧫', 3, 45),
  item('piston', 'Piston', '🛢️', 4, 200),
  item('bearing', 'Bearing', '⚪', 4, 90),
  item('boiler', 'Boiler', '♨️', 4, 700),
  item('engine_block', 'Engine Block', '🧊', 4, 1100),
  item('circuit', 'Circuit', '🖥️', 5, 130),
  item('capacitor', 'Capacitor', '🪫', 5, 100),
  item('crystal_lens', 'Crystal Lens', '💎', 5, 330),
  item('rune_plate', 'Rune Plate', '🎴', 5, 230),
  item('mana_conduit', 'Mana Conduit', '🪈', 5, 190),
  item('rune_circuit', 'Rune Circuit', '🧿', 6, 290),
  item('mana_battery', 'Mana Battery', '🔌', 6, 900),

  // ---- Tools --------------------------------------------------------------------
  item('hammer', 'Hammer', '🔨', 2, 85),
  item('saw', 'Saw', '🪚', 2, 170),
  item('chisel', 'Chisel', '🗡️', 2, 70),
  item('hatchet', 'Hatchet', '🪓', 2, 85),
  item('pickaxe', 'Pickaxe', '⛏️', 2, 130),
  item('shovel', 'Shovel', '🥄', 2, 170),
  item('anvil', 'Anvil', '🛠️', 3, 900),
  item('forge_bellows', 'Forge Bellows', '🌬️', 3, 250),
  item('scythe', 'Scythe', '🌙', 3, 170),
  item('toolbelt', 'Toolbelt', '🩹', 3, 90),
  item('measuring_kit', 'Measuring Kit', '📐', 3, 130),
  item('hand_drill', 'Hand Drill', '🌪️', 3, 260),
  item('wrench', 'Wrench', '🔧', 3, 190),
  item('magnifier', 'Magnifier', '🔎', 3, 320),
  item('power_drill', 'Power Drill', '🚧', 5, 2200),
  item('arc_welder', 'Arc Welder', '💥', 6, 1200),

  // ---- Goods ----------------------------------------------------------------------
  item('bucket', 'Bucket', '🪣', 1, 30),
  item('crate', 'Crate', '📦', 2, 45),
  item('barrel', 'Barrel', '🛢️', 2, 250),
  item('basket', 'Basket', '🧺', 2, 45),
  item('chair', 'Chair', '🪑', 2, 60),
  item('table', 'Table', '🪵', 2, 90),
  item('bed', 'Bed', '🛏️', 3, 470),
  item('cabinet', 'Cabinet', '🗄️', 3, 190),
  item('door', 'Door', '🚪', 3, 160),
  item('window', 'Window', '🪟', 3, 190),
  item('lantern', 'Lantern', '🏮', 3, 130),
  item('pottery_dishes', 'Dishes', '🍽️', 2, 20),
  item('vase', 'Painted Vase', '⚱️', 4, 130),
  item('mirror', 'Mirror', '🪞', 3, 260),
  item('spyglass', 'Spyglass', '🔭', 3, 550),
  item('clock', 'Clock', '🕰️', 4, 800),
  item('music_box', 'Music Box', '🎵', 4, 700),
  item('stove', 'Stove', '🔥', 3, 500),
  item('bathtub', 'Bathtub', '🛁', 4, 300),
  item('fountain', 'Fountain', '⛲', 4, 400),
  item('stained_glass', 'Stained Glass', '🌇', 5, 260),
  item('garment', 'Garment', '👘', 2, 90),
  item('boots', 'Boots', '🥾', 3, 120),
  item('satchel', 'Satchel', '👜', 3, 100),
  item('umbrella', 'Umbrella', '☂️', 3, 90),
  item('cart', 'Cart', '🛒', 3, 950),
  item('wheelbarrow', 'Wheelbarrow', '🚜', 3, 250),
  item('rowboat', 'Rowboat', '🛶', 3, 200),
  item('sailboat', 'Sailboat', '⛵', 4, 500),
  item('glow_lamp', 'Glow Lamp', '💡', 4, 250),
  item('arc_lamp', 'Arc Lamp', '🔦', 6, 600),

  // ---- Machines ----------------------------------------------------------------------
  item('workbench', 'Workbench', '🧰', 3, 500),
  item('sawmill', 'Sawmill', '🏭', 3, 400),
  item('kiln', 'Kiln', '🌋', 3, 300),
  item('furnace', 'Furnace', '🔥', 3, 500),
  item('blast_furnace', 'Blast Furnace', '🏭', 5, 3200),
  item('loom_machine', 'Loom', '🕸️', 3, 350),
  item('printing_press', 'Printing Press', '📰', 4, 800),
  item('water_pump', 'Water Pump', '💧', 4, 500),
  item('windmill', 'Windmill', '🌬️', 4, 500),
  item('waterwheel', 'Waterwheel', '🎡', 4, 450),
  item('steam_engine', 'Steam Engine', '🚂', 5, 2800),
  item('lathe', 'Lathe', '🧲', 5, 1900),
  item('crane', 'Crane', '🏗️', 5, 800),
  item('elevator', 'Elevator', '🛗', 5, 1300),
  item('conveyor', 'Conveyor', '➿', 4, 200),
  item('oil_pump', 'Oil Pump', '⛽', 5, 3800),
  item('refinery', 'Refinery', '🏭', 5, 1600),
  item('drill_rig', 'Drill Rig', '🗼', 6, 6000),
  item('generator', 'Generator', '⚡', 6, 4500),
  item('assembler', 'Assembler', '🦾', 6, 2800),
  item('automaton_frame', 'Automaton Frame', '🤖', 6, 900),
  item('automaton', 'Automaton', '🤖', 6, 2500),

  // ---- Arcana ----------------------------------------------------------------------
  item('incense', 'Incense', '🕯️', 2, 15),
  item('ritual_candle', 'Ritual Candle', '🕯️', 2, 15),
  item('vial', 'Glass Vial', '🧴', 3, 30),
  item('healing_potion', 'Healing Potion', '❤️', 3, 90),
  item('mana_potion', 'Mana Potion', '🌀', 4, 130),
  item('glow_potion', 'Glow Potion', '🍸', 4, 130),
  item('moon_elixir', 'Moon Elixir', '🌜', 4, 220),
  item('salt_ward', 'Salt Ward', '🧿', 5, 260),
  item('blank_scroll', 'Blank Scroll', '📜', 2, 15),
  item('scroll_of_growth', 'Scroll of Growth', '🌱', 3, 130),
  item('scroll_of_storms', 'Scroll of Storms', '🌩️', 6, 650),
  item('grimoire', 'Grimoire', '📕', 3, 200),
  item('wand', 'Wand', '🪄', 3, 140),
  item('staff', 'Staff', '🦯', 5, 400),
  item('charm', 'Charm', '🧧', 3, 120),
  item('talisman', 'Talisman', '🪬', 4, 400),
  item('rune_ring', 'Rune Ring', '💍', 5, 300),
  item('amulet', 'Amulet', '📿', 5, 550),
  item('crystal_ball', 'Crystal Ball', '🔮', 5, 400),
  item('ritual_kit', 'Ritual Kit', '🎎', 4, 120),
  item('summoning_circle', 'Summoning Circle', '🕳️', 5, 700),
  item('spirit_lantern', 'Spirit Lantern', '🎐', 5, 350),
  item('moon_mirror', 'Moon Mirror', '🌕', 5, 800),
  item('dream_catcher', 'Dream Catcher', '🕸️', 6, 550),
  item('enchanted_cloak', 'Enchanted Cloak', '🧥', 6, 600),
  item('seven_league_boots', 'Seven-League Boots', '👢', 6, 900),
  item('philosophers_salt', "Philosopher's Salt", '❄️', 5, 300),
  item('transmutation_stone', 'Transmutation Stone', '🪩', 6, 1500),
  item('potion_of_plenty', 'Potion of Plenty', '🏆', 6, 900),
  item('warding_totem', 'Warding Totem', '🗿', 5, 900),
  item('ley_chart', 'Ley Chart', '🗺️', 6, 500),
  item('spellbook', 'Spellbook', '📖', 6, 700),
  item('archmage_wand', 'Archmage Wand', '🌠', 6, 1200),
  item('phylactery', 'Phylactery', '⚗️', 7, 2600),
  item('wishing_lamp', 'Wishing Lamp', '🪔', 7, 1800),

  // ---- Magitech ----------------------------------------------------------------------
  item('golem_core', 'Golem Core', '🫀', 6, 800),
  item('stone_golem', 'Stone Golem', '🗿', 6, 1800),
  item('iron_golem', 'Iron Golem', '🦿', 6, 3200),
  item('mana_engine', 'Mana Engine', '💠', 6, 3600),
  item('clockwork_orrery', 'Clockwork Orrery', '🪐', 6, 1400),
  item('teleporter_frame', 'Teleporter Frame', '🌀', 6, 1600),
  item('teleporter', 'Teleporter', '🌌', 7, 4800),
  item('aether_compass', 'Aether Compass', '🧭', 6, 900),
  item('storm_rod', 'Storm Rod', '🌩️', 6, 800),
  item('ward_turret', 'Ward Turret', '🗼', 7, 2600),
  item('thinking_engine', 'Thinking Engine', '🧠', 7, 7500),
  item('automaton_familiar', 'Automaton Familiar', '🐦', 7, 4700),
  item('skyship_balloon', 'Skyship Balloon', '🎈', 6, 800),
  item('skyship_hull', 'Skyship Hull', '🚢', 7, 2600),
  item('skyship', 'Skyship', '🛸', 8, 12000),
  item('mana_reactor', 'Mana Reactor', '☢️', 7, 9500),

  // ---- Wonders ----------------------------------------------------------------------
  item('grand_clocktower', 'Grand Clocktower', '🏰', 8, 20000),
  item('observatory', 'Observatory', '🌠', 8, 9000),
  item('mana_well', 'Mana Well', '🕳️', 8, 15000),
  item('world_tree_sapling', 'World Tree Sapling', '🌳', 8, 8000),
  item('floating_gardens', 'Floating Gardens', '🏝️', 8, 18000),
  item('colossus', 'Colossus', '🗽', 8, 25000),
  item('leyline_nexus', 'Leyline Nexus', '💫', 8, 30000),
  item('aurora_beacon', 'Aurora Beacon', '🌌', 8, 16000),
  item('philosophers_engine', "Philosopher's Engine", '♾️', 8, 28000),
  item('arcane_citadel', 'Arcane Citadel', '🏯', 9, 100000),
];

export const RESOURCE_BY_ID: Record<string, ResourceDef> = Object.fromEntries(
  RESOURCES.map((r) => [r.id, r]),
);
