-- GENERATED by scripts/gen-unlock-sql.ts — do not edit by hand.
-- Regenerate after tech/recipe content changes with: npm run unlock-sql
--
-- Marks the whole VILLAGE research tree (500 nodes) as completed in one
-- account's cloud save, applying the same effects the engine would as each
-- node finished (completeResearch in src/engine/tick.ts): all node ids join
-- unlockedTech, and the majors' resource/recipe unlocks — plus those
-- recipes' outputs — join unlockedResources/unlockedRecipes. The research
-- queue is cleared, and savedAt/lastSeen are stamped to now so the client
-- adopts this payload on its next sign-in / app start. Multipliers are
-- recomputed from unlockedTech on load, so they are left untouched, and the
-- tournament slot is not touched at all.
--
-- Usage: adjust target_email below if needed, then run in the Supabase SQL
-- editor (or psql, as a role with access to auth.users). Run while the
-- player is NOT actively playing — an open tab pushes its local state on a
-- timer and would overwrite this — then have them reload the app.

do $$
declare
  target_email constant text := 'therichfull@gmail.com';

  -- Every village tech node id.
  all_tech constant jsonb := '[
    "basic_tools", "woodworking", "quarrying", "metallurgy", "ironworking", "toolmaking",
    "carpentry", "claywork", "steelworks", "glassworks", "mechanisms", "construction",
    "fine_machinery", "plumbing", "chemistry", "transport", "everyday_engineering",
    "steam_power", "railworks", "oil_age", "electricity", "communications", "automation",
    "rope_making", "sapcraft", "herbalism", "weaving", "alchemy", "ambercraft", "scrivenery",
    "sporecraft", "lunar_rites", "vitalism", "divination", "crystal_attunement",
    "high_rituals", "enchantment", "ley_mastery", "spirit_pistons", "rune_engineering",
    "voltite_arcana", "aetherworks", "wonders_of_spirit", "arcane_engine", "golemcraft",
    "runic_industry", "arcane_machinery", "thinking_machines", "wonders_of_matter",
    "sharp_tools", "jigs_fixtures", "ore_roasting", "bloomery_draft", "standard_parts",
    "hot_blast", "fine_tooling", "wood_attunement", "sap_flow", "verdant_whisper",
    "deep_roots", "spring_song", "moon_tides", "mortar_pestle", "sap_harvest",
    "quill_cutting", "spore_prints", "night_vigils", "living_cultures", "tea_leaves",
    "crystal_songs", "runic_saws", "spirit_valves", "spirit_beacons", "etched_cylinders",
    "mana_gaskets", "rune_benches", "charged_etchings", "storm_watching", "copper_runes",
    "sky_trials", "lift_theory", "aether_sails", "horizon_charts", "high_altars",
    "mana_lathe", "singing_gears", "humming_frames", "clay_effigies", "binding_words",
    "waking_rites", "work_chants", "golem_foremen", "rune_stencils", "mana_flywheels",
    "alloy_trials", "logic_runes", "memory_crystals", "grand_designs", "tempered_fittings",
    "milled_fittings", "riveted_fittings", "calibrated_fittings", "forged_fittings",
    "beveled_fittings", "geared_fittings", "bolted_fittings", "polished_fittings",
    "reinforced_fittings", "machined_fittings", "cast_fittings", "welded_fittings",
    "balanced_fittings", "hardened_fittings", "threaded_fittings", "pressed_fittings",
    "turned_fittings", "braced_fittings", "ground_fittings", "soldered_fittings",
    "stamped_fittings", "jointed_fittings", "tuned_fittings", "tempered_gauges",
    "milled_gauges", "riveted_gauges", "calibrated_gauges", "forged_gauges",
    "beveled_gauges", "geared_gauges", "bolted_gauges", "polished_gauges",
    "reinforced_gauges", "machined_gauges", "cast_gauges", "welded_gauges",
    "balanced_gauges", "hardened_gauges", "threaded_gauges", "pressed_gauges",
    "turned_gauges", "braced_gauges", "ground_gauges", "soldered_gauges", "stamped_gauges",
    "jointed_gauges", "tuned_gauges", "tempered_ratchets", "milled_ratchets",
    "riveted_ratchets", "calibrated_ratchets", "forged_ratchets", "beveled_ratchets",
    "geared_ratchets", "bolted_ratchets", "polished_ratchets", "reinforced_ratchets",
    "machined_ratchets", "cast_ratchets", "welded_ratchets", "balanced_ratchets",
    "hardened_ratchets", "threaded_ratchets", "pressed_ratchets", "turned_ratchets",
    "braced_ratchets", "ground_ratchets", "soldered_ratchets", "stamped_ratchets",
    "jointed_ratchets", "tuned_ratchets", "tempered_levers", "milled_levers",
    "riveted_levers", "calibrated_levers", "forged_levers", "beveled_levers",
    "geared_levers", "bolted_levers", "polished_levers", "reinforced_levers",
    "machined_levers", "cast_levers", "welded_levers", "silvered_charms", "moonlit_charms",
    "hallowed_charms", "fey_charms", "sylvan_charms", "runeswept_charms", "emberlit_charms",
    "dusken_charms", "starbound_charms", "veiled_charms", "blooming_charms",
    "whistling_charms", "glimmering_charms", "hollow_charms", "elder_charms",
    "twilight_charms", "dewkissed_charms", "wandering_charms", "thorned_charms",
    "mistborn_charms", "sacred_charms", "umbral_charms", "radiant_charms",
    "murmuring_charms", "silvered_sigils", "moonlit_sigils", "hallowed_sigils", "fey_sigils",
    "sylvan_sigils", "runeswept_sigils", "emberlit_sigils", "dusken_sigils",
    "starbound_sigils", "veiled_sigils", "blooming_sigils", "whistling_sigils",
    "glimmering_sigils", "hollow_sigils", "elder_sigils", "twilight_sigils",
    "dewkissed_sigils", "wandering_sigils", "thorned_sigils", "mistborn_sigils",
    "sacred_sigils", "umbral_sigils", "radiant_sigils", "murmuring_sigils", "silvered_omens",
    "moonlit_omens", "hallowed_omens", "fey_omens", "sylvan_omens", "runeswept_omens",
    "emberlit_omens", "dusken_omens", "starbound_omens", "enchanted_conduits",
    "runic_conduits", "arcane_conduits", "attuned_conduits", "sparkbound_conduits",
    "hexwired_conduits", "sigiled_conduits", "manaforged_conduits", "balanced_levers",
    "hardened_levers", "threaded_levers", "pressed_levers", "turned_levers", "braced_levers",
    "ground_levers", "soldered_levers", "etheric_conduits", "charged_conduits",
    "warded_conduits", "resonant_conduits", "veiled_omens", "blooming_omens",
    "whistling_omens", "glimmering_omens", "hollow_omens", "elder_omens", "twilight_omens",
    "dewkissed_omens", "wandering_omens", "thorned_omens", "mistborn_omens", "sacred_omens",
    "spellwrought_conduits", "voltaic_conduits", "inscribed_conduits", "animated_conduits",
    "leybound_conduits", "glowforged_conduits", "thaumic_conduits", "astral_conduits",
    "empowered_conduits", "conjured_conduits", "galvanic_conduits", "transmuted_conduits",
    "bespelled_conduits", "ensorcelled_conduits", "fluxbound_conduits", "gildwired_conduits",
    "hallowired_conduits", "ironsung_conduits", "manalit_conduits", "runefused_conduits",
    "enchanted_regulators", "runic_regulators", "arcane_regulators", "attuned_regulators",
    "sparkbound_regulators", "hexwired_regulators", "sigiled_regulators",
    "manaforged_regulators", "etheric_regulators", "charged_regulators", "warded_regulators",
    "resonant_regulators", "spellwrought_regulators", "voltaic_regulators",
    "inscribed_regulators", "animated_regulators", "leybound_regulators",
    "glowforged_regulators", "thaumic_regulators", "astral_regulators",
    "empowered_regulators", "conjured_regulators", "galvanic_regulators",
    "transmuted_regulators", "bespelled_regulators", "ensorcelled_regulators",
    "fluxbound_regulators", "gildwired_regulators", "hallowired_regulators",
    "ironsung_regulators", "manalit_regulators", "runefused_regulators", "enchanted_dynamos",
    "runic_dynamos", "arcane_dynamos", "attuned_dynamos", "sparkbound_dynamos",
    "hexwired_dynamos", "sigiled_dynamos", "manaforged_dynamos", "etheric_dynamos",
    "charged_dynamos", "warded_dynamos", "stamped_levers", "jointed_levers", "tuned_levers",
    "tempered_couplings", "milled_couplings", "riveted_couplings", "calibrated_couplings",
    "resonant_dynamos", "spellwrought_dynamos", "voltaic_dynamos", "inscribed_dynamos",
    "animated_dynamos", "umbral_omens", "radiant_omens", "murmuring_omens",
    "silvered_blessings", "moonlit_blessings", "hallowed_blessings", "leybound_dynamos",
    "glowforged_dynamos", "thaumic_dynamos", "astral_dynamos", "empowered_dynamos",
    "conjured_dynamos", "galvanic_dynamos", "transmuted_dynamos", "bespelled_dynamos",
    "ensorcelled_dynamos", "fluxbound_dynamos", "gildwired_dynamos", "forged_couplings",
    "beveled_couplings", "geared_couplings", "bolted_couplings", "polished_couplings",
    "reinforced_couplings", "hallowired_dynamos", "ironsung_dynamos", "manalit_dynamos",
    "runefused_dynamos", "enchanted_actuators", "runic_actuators", "arcane_actuators",
    "attuned_actuators", "sparkbound_actuators", "hexwired_actuators", "sigiled_actuators",
    "manaforged_actuators", "etheric_actuators", "charged_actuators", "warded_actuators",
    "resonant_actuators", "spellwrought_actuators", "fey_blessings", "sylvan_blessings",
    "runeswept_blessings", "emberlit_blessings", "dusken_blessings", "starbound_blessings",
    "voltaic_actuators", "inscribed_actuators", "animated_actuators", "leybound_actuators",
    "glowforged_actuators", "thaumic_actuators", "astral_actuators", "empowered_actuators",
    "conjured_actuators", "galvanic_actuators", "transmuted_actuators",
    "bespelled_actuators", "ensorcelled_actuators", "fluxbound_actuators",
    "gildwired_actuators", "machined_couplings", "cast_couplings", "welded_couplings",
    "balanced_couplings", "hallowired_actuators", "ironsung_actuators", "manalit_actuators",
    "runefused_actuators", "enchanted_matrices", "runic_matrices", "arcane_matrices",
    "attuned_matrices", "sparkbound_matrices", "hexwired_matrices", "sigiled_matrices",
    "manaforged_matrices", "etheric_matrices", "charged_matrices", "warded_matrices",
    "resonant_matrices", "spellwrought_matrices", "voltaic_matrices", "inscribed_matrices",
    "animated_matrices", "leybound_matrices", "glowforged_matrices", "thaumic_matrices",
    "astral_matrices", "empowered_matrices", "conjured_matrices", "galvanic_matrices",
    "transmuted_matrices", "bespelled_matrices", "ensorcelled_matrices",
    "fluxbound_matrices", "gildwired_matrices", "hallowired_matrices", "ironsung_matrices",
    "manalit_matrices", "runefused_matrices", "enchanted_resonators", "runic_resonators",
    "hardened_couplings", "threaded_couplings", "pressed_couplings", "veiled_blessings",
    "blooming_blessings", "whistling_blessings", "glimmering_blessings", "hollow_blessings",
    "elder_blessings", "twilight_blessings", "dewkissed_blessings", "wandering_blessings",
    "thorned_blessings", "mistborn_blessings", "sacred_blessings", "umbral_blessings",
    "radiant_blessings", "murmuring_blessings", "silvered_glyphs", "moonlit_glyphs",
    "hallowed_glyphs", "fey_glyphs", "arcane_resonators", "attuned_resonators",
    "sparkbound_resonators", "hexwired_resonators", "sigiled_resonators",
    "manaforged_resonators", "etheric_resonators", "charged_resonators", "warded_resonators",
    "resonant_resonators", "spellwrought_resonators", "voltaic_resonators",
    "inscribed_resonators", "animated_resonators", "leybound_resonators",
    "glowforged_resonators", "thaumic_resonators", "astral_resonators",
    "empowered_resonators", "conjured_resonators", "galvanic_resonators",
    "transmuted_resonators", "bespelled_resonators", "ensorcelled_resonators",
    "fluxbound_resonators", "gildwired_resonators", "hallowired_resonators"
  ]';

  -- Resources granted by tech effects, plus outputs of tech-unlocked recipes.
  all_resources constant jsonb := '[
    "plank", "paper", "stone", "stone_brick", "copper_ore", "iron_ore", "copper_ingot",
    "coal", "charcoal", "iron_ingot", "nails", "iron_rod", "iron_plate", "copper_wire",
    "gear", "furnace", "forge_bellows", "handle", "hammer", "saw", "chisel", "hatchet",
    "pickaxe", "shovel", "wooden_beam", "wooden_frame", "crate", "bucket", "table", "chair",
    "barrel", "clay", "brick", "ceramic", "pottery_dishes", "kiln", "steel", "steel_plate",
    "blade", "spring", "bolt_kit", "chain", "anvil", "scythe", "blast_furnace",
    "quartz_sand", "glass", "lens", "glass_tube", "window", "mirror", "spyglass", "vial",
    "lantern", "hinge", "bracket", "crank", "pulley_block", "wheel", "axle_assembly",
    "gearbox", "sawmill", "waterwheel", "windmill", "loom_machine", "stone_pillar", "arch",
    "door", "cabinet", "workbench", "stove", "clock", "music_box", "printing_press",
    "measuring_kit", "hand_drill", "wrench", "magnifier", "pipe", "valve", "water_pump",
    "bathtub", "fountain", "boiler", "sulfur", "black_powder", "rubber", "boots", "umbrella",
    "conveyor", "cart", "wheelbarrow", "rowboat", "sailboat", "bicycle", "typewriter",
    "piston", "bearing", "engine_block", "steam_engine", "lathe", "crane", "elevator",
    "rail_track", "locomotive", "crude_oil", "plastic", "oil_pump", "refinery",
    "power_drill", "drill_rig", "voltite", "circuit", "capacitor", "voltite_cell",
    "generator", "arc_welder", "arc_lamp", "telegraph", "camera", "assembler",
    "automaton_frame", "automaton", "fiber", "rope", "resin", "glue", "barkhide",
    "ritual_candle", "herbs", "herbal_extract", "spirit_water", "incense", "cloth", "basket",
    "garment", "satchel", "bed", "toolbelt", "salt", "healing_potion", "salt_ward", "amber",
    "amber_pearl", "charm", "wand", "blank_scroll", "enchanted_ink", "scroll_of_growth",
    "grimoire", "glowspore", "glow_paste", "glow_potion", "glow_lamp", "moon_dew",
    "moon_elixir", "moon_silver", "moon_mirror", "talisman", "homunculus", "vitae_flask",
    "fortune_deck", "singing_bowl", "mana_crystal", "mana_dust", "mana_potion", "rune_stone",
    "crystal_ball", "rune_ring", "staff", "ritual_kit", "summoning_circle", "warding_totem",
    "spirit_lantern", "philosophers_salt", "amulet", "enchanted_cloak", "seven_league_boots",
    "spellbook", "archmage_wand", "ley_essence", "ley_thread", "ley_chart", "dream_catcher",
    "transmutation_stone", "phylactery", "wishing_lamp", "potion_of_plenty", "rune_plate",
    "mana_conduit", "crystal_lens", "stained_glass", "vase", "storm_rod", "mana_battery",
    "rune_circuit", "scroll_of_storms", "skyship_balloon", "skyship_hull", "skyship",
    "aether_compass", "mana_well", "world_tree_sapling", "floating_gardens", "leyline_nexus",
    "aurora_beacon", "arcane_citadel", "arcane_alloy", "golem_core", "stone_golem",
    "iron_golem", "rune_press", "lightning_loom", "levitation_disc", "mana_engine",
    "clockwork_orrery", "teleporter_frame", "thinking_engine", "automaton_familiar",
    "ward_turret", "teleporter", "mana_reactor", "colossus", "grand_clocktower",
    "observatory", "philosophers_engine"
  ]';

  -- Recipes granted by tech effects.
  all_recipes constant jsonb := '[
    "planks", "paper", "stone_brick", "copper_ingot", "charcoal", "iron_ingot", "nails",
    "iron_rod", "iron_plate", "copper_wire", "gear", "furnace", "forge_bellows", "handle",
    "hammer", "saw", "chisel", "hatchet", "pickaxe", "shovel", "wooden_beam", "wooden_frame",
    "crate", "bucket", "table", "chair", "barrel", "brick", "ceramic", "pottery_dishes",
    "kiln", "steel", "steel_plate", "blade", "spring", "bolt_kit", "chain", "anvil",
    "scythe", "blast_furnace", "glass", "lens", "glass_tube", "window", "mirror", "spyglass",
    "vial", "lantern", "hinge", "bracket", "crank", "pulley_block", "wheel", "axle_assembly",
    "gearbox", "sawmill", "waterwheel", "windmill", "loom_machine", "stone_pillar", "arch",
    "door", "cabinet", "workbench", "stove", "clock", "music_box", "printing_press",
    "measuring_kit", "hand_drill", "wrench", "magnifier", "pipe", "valve", "water_pump",
    "bathtub", "fountain", "boiler", "black_powder", "rubber", "boots", "umbrella",
    "conveyor", "cart", "wheelbarrow", "rowboat", "sailboat", "bicycle", "typewriter",
    "piston", "bearing", "engine_block", "steam_engine", "lathe", "crane", "elevator",
    "rail_track", "locomotive", "plastic", "oil_pump", "refinery", "power_drill",
    "drill_rig", "circuit", "capacitor", "voltite_cell", "generator", "arc_welder",
    "arc_lamp", "telegraph", "camera", "assembler", "automaton_frame", "automaton", "rope",
    "glue", "barkhide", "ritual_candle", "herbal_extract", "spirit_water", "incense",
    "cloth", "basket", "garment", "satchel", "bed", "toolbelt", "healing_potion",
    "salt_ward", "amber_pearl", "charm", "wand", "blank_scroll", "enchanted_ink",
    "scroll_of_growth", "grimoire", "glow_paste", "glow_potion", "glow_lamp", "moon_elixir",
    "moon_silver", "moon_mirror", "talisman", "homunculus", "vitae_flask", "fortune_deck",
    "singing_bowl", "mana_dust", "mana_potion", "rune_stone", "crystal_ball", "rune_ring",
    "staff", "ritual_kit", "summoning_circle", "warding_totem", "spirit_lantern",
    "philosophers_salt", "amulet", "enchanted_cloak", "seven_league_boots", "spellbook",
    "archmage_wand", "ley_thread", "ley_chart", "dream_catcher", "transmutation_stone",
    "phylactery", "wishing_lamp", "potion_of_plenty", "rune_plate", "mana_conduit",
    "crystal_lens", "stained_glass", "vase", "storm_rod", "mana_battery", "rune_circuit",
    "scroll_of_storms", "skyship_balloon", "skyship_hull", "skyship", "aether_compass",
    "mana_well", "world_tree_sapling", "floating_gardens", "leyline_nexus", "aurora_beacon",
    "arcane_citadel", "arcane_alloy", "golem_core", "stone_golem", "iron_golem",
    "rune_press", "lightning_loom", "levitation_disc", "mana_engine", "clockwork_orrery",
    "teleporter_frame", "thinking_engine", "automaton_familiar", "ward_turret", "teleporter",
    "mana_reactor", "colossus", "grand_clocktower", "observatory", "philosophers_engine"
  ]';

  now_ms constant bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  uid uuid;
  slot jsonb;
begin
  select u.id into uid from auth.users u where lower(u.email) = lower(target_email);
  if uid is null then
    raise exception 'no auth user with email %', target_email;
  end if;

  select s.payload #> '{slots,main}' into slot from public.saves s where s.user_id = uid;
  if slot is null then
    raise exception 'no cloud save with a village slot for % — the account must play and back up once first',
      target_email;
  end if;

  -- Union each unlock list with the full set, keeping anything already there.
  slot := slot || jsonb_build_object(
    'unlockedTech', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedTech', '[]'::jsonb) || all_tech) as t(v)
    ),
    'unlockedResources', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedResources', '[]'::jsonb) || all_resources) as t(v)
    ),
    'unlockedRecipes', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedRecipes', '[]'::jsonb) || all_recipes) as t(v)
    ),
    'researchQueue', '[]'::jsonb,
    'researchProgress', 0,
    'lastSeen', now_ms
  );

  update public.saves s
  set payload = jsonb_set(jsonb_set(s.payload, '{slots,main}', slot), '{savedAt}', to_jsonb(now_ms))
  where s.user_id = uid;

  raise notice 'village tree fully unlocked for % (% tech nodes)',
    target_email, jsonb_array_length(all_tech);
end $$;
