// Generates supabase/scripts/unlock_village_research.sql — run with
// `npm run unlock-sql` (optionally `-- someone@example.com` to bake a
// different default target account into the file).
//
// The village tree's 500 node ids (400 of them generated fillers) and the
// majors' unlock effects only exist in src/content, so the SQL's id lists
// have to be baked from the same source the game ships. For every village
// node this mirrors what the engine applies when research finishes
// (completeResearch in src/engine/tick.ts): the node id joins unlockedTech,
// unlockResource/unlockRecipe effects join the unlock lists, and unlocked
// recipes reveal their outputs. Regenerate after any tech or recipe change.
import { mkdirSync, writeFileSync } from 'node:fs';
import { RECIPE_BY_ID } from '../src/content/recipes';
import { techTree } from '../src/content/tech';

const email = process.argv[2] ?? 'therichfull@gmail.com';

const tree = techTree('main');
const techIds = tree.map((n) => n.id);
const resourceIds = new Set<string>();
const recipeIds = new Set<string>();
for (const node of tree) {
  for (const effect of node.effects) {
    if (effect.kind === 'unlockResource') {
      resourceIds.add(effect.id);
    } else if (effect.kind === 'unlockRecipe') {
      recipeIds.add(effect.id);
      for (const id of Object.keys(RECIPE_BY_ID[effect.id]?.outputs ?? {})) {
        resourceIds.add(id);
      }
    }
  }
}

// A '["a", "b", ...]' jsonb literal, line-wrapped for readable diffs.
function jsonbArray(ids: string[]): string {
  const lines: string[] = [];
  let line = '';
  for (const id of ids) {
    const piece = `"${id}"`;
    if (line && `${line}, ${piece}`.length > 88) {
      lines.push(`${line},`);
      line = piece;
    } else {
      line = line ? `${line}, ${piece}` : piece;
    }
  }
  lines.push(line);
  return `'[\n    ${lines.join('\n    ')}\n  ]'`;
}

const sql = `-- GENERATED by scripts/gen-unlock-sql.ts — do not edit by hand.
-- Regenerate after tech/recipe content changes with: npm run unlock-sql
--
-- Marks the whole VILLAGE research tree (${techIds.length} nodes) as completed in one
-- account's cloud save, applying the same effects the engine would as each
-- node finished (completeResearch in src/engine/tick.ts): all node ids join
-- unlockedTech, and the majors' resource/recipe unlocks — plus those
-- recipes' outputs — join unlockedResources/unlockedRecipes. The research
-- queue is cleared, and savedAt/lastSeen are stamped to now so the client
-- adopts this payload on its next sign-in / app start. Multipliers are
-- recomputed from unlockedTech on load, so they are left untouched, and the
-- tournament slot is not touched at all.
--
-- Usage: adjust target_email below if needed, then run in the Supabase SQL
-- editor (or psql, as a role with access to auth.users). Run while the
-- player is NOT actively playing — an open tab pushes its local state on a
-- timer and would overwrite this — then have them reload the app.

do $$
declare
  target_email constant text := '${email}';

  -- Every village tech node id.
  all_tech constant jsonb := ${jsonbArray(techIds)};

  -- Resources granted by tech effects, plus outputs of tech-unlocked recipes.
  all_resources constant jsonb := ${jsonbArray([...resourceIds])};

  -- Recipes granted by tech effects.
  all_recipes constant jsonb := ${jsonbArray([...recipeIds])};

  now_ms constant bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  uid uuid;
  slot jsonb;
begin
  select u.id into uid from auth.users u where lower(u.email) = lower(target_email);
  if uid is null then
    raise exception 'no auth user with email %', target_email;
  end if;

  select s.payload #> '{slots,main}' into slot from public.saves s where s.user_id = uid;
  if slot is null then
    raise exception 'no cloud save with a village slot for % — the account must play and back up once first',
      target_email;
  end if;

  -- Union each unlock list with the full set, keeping anything already there.
  slot := slot || jsonb_build_object(
    'unlockedTech', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedTech', '[]'::jsonb) || all_tech) as t(v)
    ),
    'unlockedResources', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedResources', '[]'::jsonb) || all_resources) as t(v)
    ),
    'unlockedRecipes', (
      select jsonb_agg(distinct v)
      from jsonb_array_elements(coalesce(slot -> 'unlockedRecipes', '[]'::jsonb) || all_recipes) as t(v)
    ),
    'researchQueue', '[]'::jsonb,
    'researchProgress', 0,
    'lastSeen', now_ms
  );

  update public.saves s
  set payload = jsonb_set(jsonb_set(s.payload, '{slots,main}', slot), '{savedAt}', to_jsonb(now_ms))
  where s.user_id = uid;

  raise notice 'village tree fully unlocked for % (% tech nodes)',
    target_email, jsonb_array_length(all_tech);
end $$;
`;

mkdirSync(new URL('../supabase/scripts/', import.meta.url), { recursive: true });
const out = new URL('../supabase/scripts/unlock_village_research.sql', import.meta.url);
writeFileSync(out, sql);
console.log(
  `wrote supabase/scripts/unlock_village_research.sql — ` +
    `${techIds.length} tech, ${recipeIds.size} recipes, ${resourceIds.size} resources, target ${email}`,
);
